In [1]:
import pandas as pd
import numpy as np

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime_Reports.csv')
print(dfCrime.shape)
dfCrime.head()

(2613106, 19)

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,Location Type,Council District,APD Sector,APD District,Clearance Status,Clearance Date,UCR Category,Category Description,Census Block Group
0,2006761045,CRIMINAL MISCHIEF,1400,N,03/17/2006 13:06,03/17/2006,1306.0,03/17/2006 13:06,03/17/2006,1306.0,RESIDENCE / HOME,NaN,88,88,NaN,NaN,NaN,NaN,NaN
1,2006761134,PUBLIC INTOXICATION,2300,N,03/17/2006 14:10,03/17/2006,1410.0,03/17/2006 14:10,03/17/2006,1410.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,NaN,GE,3,NaN,NaN,NaN,NaN,NaN
2,2006691217,THEFT,600,N,03/10/2006 14:15,03/10/2006,1415.0,03/10/2006 14:30,03/10/2006,1430.0,GROCERY / SUPERMARKET,5.0,FR,1,NaN,NaN,23H,Theft,4.530318e+09
3,20065014461,HARASSMENT,2703,N,10/01/2005 08:00,10/01/2005,800.0,03/21/2006 10:50,03/21/2006,1050.0,RESIDENCE / HOME,5.0,DA,3,NaN,03/31/2006,NaN,NaN,4.530020e+09
4,2006692344,THEFT,600,N,02/09/2006 22:39,02/09/2006,2239.0,02/09/2006 22:39,02/09/2006,2239.0,RESIDENCE / HOME,2.0,FR,8,N,03/21/2006,23H,Theft,4.530024e+09

In [3]:
dfCrime['Occurred Date'] = pd.to_datetime(dfCrime['Occurred Date'])
dfCrime.head()

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,Location Type,Council District,APD Sector,APD District,Clearance Status,Clearance Date,UCR Category,Category Description,Census Block Group
0,2006761045,CRIMINAL MISCHIEF,1400,N,03/17/2006 13:06,2006-03-17,1306.0,03/17/2006 13:06,03/17/2006,1306.0,RESIDENCE / HOME,NaN,88,88,NaN,NaN,NaN,NaN,NaN
1,2006761134,PUBLIC INTOXICATION,2300,N,03/17/2006 14:10,2006-03-17,1410.0,03/17/2006 14:10,03/17/2006,1410.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,NaN,GE,3,NaN,NaN,NaN,NaN,NaN
2,2006691217,THEFT,600,N,03/10/2006 14:15,2006-03-10,1415.0,03/10/2006 14:30,03/10/2006,1430.0,GROCERY / SUPERMARKET,5.0,FR,1,NaN,NaN,23H,Theft,4.530318e+09
3,20065014461,HARASSMENT,2703,N,10/01/2005 08:00,2005-10-01,800.0,03/21/2006 10:50,03/21/2006,1050.0,RESIDENCE / HOME,5.0,DA,3,NaN,03/31/2006,NaN,NaN,4.530020e+09
4,2006692344,THEFT,600,N,02/09/2006 22:39,2006-02-09,2239.0,02/09/2006 22:39,02/09/2006,2239.0,RESIDENCE / HOME,2.0,FR,8,N,03/21/2006,23H,Theft,4.530024e+09

In [5]:
dfCrime = dfCrime.loc[(dfCrime['Occurred Date'] >= '2017-01-01') & (dfCrime['Occurred Date'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(309515, 19)

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,Location Type,Council District,APD Sector,APD District,Clearance Status,Clearance Date,UCR Category,Category Description,Census Block Group
1819156,201710262,PUBLIC INTOXICATION,2300,N,01/01/2017 01:00,2017-01-01,100.0,01/01/2017 16:52,01/01/2017,1652.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,9.0,GE,2,C,01/03/2017,NaN,NaN,4.530011e+09
1819157,201710133,DEADLY CONDUCT,408,N,01/01/2017 00:24,2017-01-01,24.0,01/01/2017 00:24,01/01/2017,24.0,RESIDENCE / HOME,2.0,FR,5,N,02/14/2017,13A,Aggravated Assault,4.530024e+09
1819158,201710546,ASSAULT WITH INJURY,900,N,01/01/2017 03:27,2017-01-01,327.0,01/01/2017 03:27,01/01/2017,327.0,BAR / NIGHTCLUB,9.0,GE,2,N,01/13/2017,NaN,NaN,4.530011e+09
1819166,201710046,AGG ASSAULT,402,N,01/01/2017 00:07,2017-01-01,7.0,01/01/2017 00:07,01/01/2017,7.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,9.0,GE,2,NaN,NaN,13A,Aggravated Assault,4.530011e+09
1819167,201710498,PUBLIC INTOXICATION,2300,N,01/01/2017 02:01,2017-01-01,201.0,01/01/2017 02:01,01/01/2017,201.0,HOTEL / MOTEL / ETC.,7.0,AD,1,C,01/01/2017,NaN,NaN,4.530454e+09

In [6]:
list(dfCrime['Category Description'].unique())

[nan,
 'Aggravated Assault',
 'Theft',
 'Rape',
 'Auto Theft',
 'Robbery',
 'Burglary',
 'Murder']

In [7]:
dfCrime = dfCrime[dfCrime['Category Description'].isna() == False]
dfCrime.shape

(112037, 19)

In [8]:
dfCrime = dfCrime[dfCrime['Census Block Group'].isnull() == False]
dfCrime['Census Block Group'] = dfCrime['Census Block Group'].apply(lambda x: f"{x:.0f}")
dfCrime['Census Block Group'] = '48' + dfCrime['Census Block Group']
dfCrime['AFFGEOID'] = '1500000US' + dfCrime['Census Block Group']
print(dfCrime.shape)
dfCrime.head()

(111028, 20)

,Incident Number,Highest Offense Description,Highest Offense Code,Family Violence,Occurred Date Time,Occurred Date,Occurred Time,Report Date Time,Report Date,Report Time,Location Type,Council District,APD Sector,APD District,Clearance Status,Clearance Date,UCR Category,Category Description,Census Block Group,AFFGEOID
1819157,201710133,DEADLY CONDUCT,408,N,01/01/2017 00:24,2017-01-01,24.0,01/01/2017 00:24,01/01/2017,24.0,RESIDENCE / HOME,2.0,FR,5,N,02/14/2017,13A,Aggravated Assault,484530024123,1500000US484530024123
1819166,201710046,AGG ASSAULT,402,N,01/01/2017 00:07,2017-01-01,7.0,01/01/2017 00:07,01/01/2017,7.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,9.0,GE,2,NaN,NaN,13A,Aggravated Assault,484530011011,1500000US484530011011
1819182,20175000014,BURGLARY OF VEHICLE,601,N,01/01/2017 07:40,2017-01-01,740.0,01/01/2017 08:40,01/01/2017,840.0,RESIDENCE / HOME,9.0,GE,1,N,01/03/2017,23F,Theft,484530012004,1500000US484530012004
1819184,201710572,AGG ASSAULT,402,N,01/01/2017 02:16,2017-01-01,216.0,01/01/2017 02:16,01/01/2017,216.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,9.0,GE,2,N,01/13/2017,13A,Aggravated Assault,484530011011,1500000US484530011011
1819186,201711078,TAKE WEAPON FROM POLICE OFFICER,409,N,01/01/2017 05:25,2017-01-01,525.0,01/01/2017 05:25,01/01/2017,525.0,HWY / ROAD / ALLEY/ STREET/ SIDEWALK,1.0,CH,6,O,01/01/2017,13A,Aggravated Assault,484530022143,1500000US484530022143

In [9]:
crime = dfCrime['AFFGEOID'].value_counts() / 3
crime = pd.DataFrame(crime)
print(crime.shape)
crime.head()

(684, 1)

                            count
AFFGEOID
1500000US484530011011  815.000000
1500000US484530324001  479.666667
1500000US484530011032  467.666667
1500000US484530403003  422.000000
1500000US484530021054  379.333333

In [17]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/AustinTX_all_crime_by_BG.csv')

In [19]:
violentCrimes = ['Aggravated Assault', 'Rape', 'Robbery', 'Murder']
dfViolentCrime = dfCrime[dfCrime['Category Description'].isin(violentCrimes)]
crime = dfViolentCrime['AFFGEOID'].value_counts() / 3
crime = pd.DataFrame(crime)
print(crime.shape)
crime.head()

(621, 1)

                            count
AFFGEOID
1500000US484530011011  139.000000
1500000US484530011032   44.666667
1500000US484530021054   44.333333
1500000US484530407003   38.666667
1500000US484530410002   38.666667

In [21]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/AustinTX_violent_crime_by_BG.csv')

In [23]:
propertyCrimes = ['Theft', 'Auto Theft', 'Burglary']
dfPropertyCrime = dfCrime[dfCrime['Category Description'].isin(propertyCrimes)]
crime = dfPropertyCrime['AFFGEOID'].value_counts() / 3
crime = pd.DataFrame(crime)
print(crime.shape)
crime.head()

(675, 1)

                            count
AFFGEOID
1500000US484530011011  676.000000
1500000US484530324001  470.666667
1500000US484530011032  423.000000
1500000US484530403003  397.000000
1500000US484530454003  346.333333

In [25]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/AustinTX_property_crime_by_BG.csv')

In [27]:
propertyCrimes = ['Auto Theft']
dfPropertyCrime = dfCrime[dfCrime['Category Description'].isin(propertyCrimes)]
crime = dfPropertyCrime['AFFGEOID'].value_counts() / 3
crime = pd.DataFrame(crime)
print(crime.shape)
crime.head()

(602, 1)

                           count
AFFGEOID
1500000US484530011011  26.333333
1500000US484530454003  26.000000
1500000US484530009024  20.333333
1500000US484539800001  19.000000
1500000US484530023221  18.333333

In [29]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/AustinTX_MV_crime_by_BG.csv')