In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime.csv')
print(dfCrime.shape)
dfCrime.head()

(438822, 30)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_8694/1590329121.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime.csv')

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,Start_Date_Time,End_Date_Time,NIBRS Code,Victims,Crime Name1,Crime Name2,...,PRA,Address Number,Street Prefix,Street Name,Street Suffix,Street Type,Latitude,Longitude,Police District Number,Location
0,201166610,2308,170548599,NaN,12/14/2017 04:30:00 PM,NaN,23D,1,Crime Against Property,Theft from Building,...,270,1700.0,E,JEFFERSON,NaN,ST,39.05848,-77.1264,1D,"(39.0585, -77.1264)"
1,201359823,5404,220000965,01/09/2022 01:18:38 AM,01/09/2022 01:34:00 AM,NaN,90D,1,Crime Against Society,Driving Under the Influence,...,428,100.0,N,FREDERICK,NaN,AVE,39.09438,-77.1517,6D,"(39.0944, -77.1517)"
2,201095140,2303,16043118,NaN,08/24/2016 09:47:00 PM,NaN,23C,1,Crime Against Property,Shoplifting,...,271,5700.0,NaN,BOU,NaN,AVE,39.05597,-77.1136,1D,"(39.056, -77.1136)"
3,201090710,5707,16037677,NaN,07/25/2016 05:31:00 PM,NaN,90J,1,Crime Against Society,Trespass of Real Property,...,321,11100.0,NaN,VEIRS MILL,NaN,RD,39.03758,-77.0519,4D,"(39.0376, -77.0519)"
4,201362142,2901,220003839,01/28/2022 07:11:29 PM,01/28/2022 02:40:00 PM,01/28/2022 02:46:00 PM,290,1,Crime Against Property,Destruction/Damage/Vandalism of Property,...,545,18500.0,N,FREDERICK,NaN,AVE,39.16059,-77.2209,6D,"(39.1606, -77.2209)"

In [3]:
dfCrime['Start_Date_Time'] = pd.to_datetime(dfCrime['Start_Date_Time'])
dfCrime.head()

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_8694/1499690141.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  dfCrime['Start_Date_Time'] = pd.to_datetime(dfCrime['Start_Date_Time'])

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,Start_Date_Time,End_Date_Time,NIBRS Code,Victims,Crime Name1,Crime Name2,...,PRA,Address Number,Street Prefix,Street Name,Street Suffix,Street Type,Latitude,Longitude,Police District Number,Location
0,201166610,2308,170548599,NaN,2017-12-14 16:30:00,NaN,23D,1,Crime Against Property,Theft from Building,...,270,1700.0,E,JEFFERSON,NaN,ST,39.05848,-77.1264,1D,"(39.0585, -77.1264)"
1,201359823,5404,220000965,01/09/2022 01:18:38 AM,2022-01-09 01:34:00,NaN,90D,1,Crime Against Society,Driving Under the Influence,...,428,100.0,N,FREDERICK,NaN,AVE,39.09438,-77.1517,6D,"(39.0944, -77.1517)"
2,201095140,2303,16043118,NaN,2016-08-24 21:47:00,NaN,23C,1,Crime Against Property,Shoplifting,...,271,5700.0,NaN,BOU,NaN,AVE,39.05597,-77.1136,1D,"(39.056, -77.1136)"
3,201090710,5707,16037677,NaN,2016-07-25 17:31:00,NaN,90J,1,Crime Against Society,Trespass of Real Property,...,321,11100.0,NaN,VEIRS MILL,NaN,RD,39.03758,-77.0519,4D,"(39.0376, -77.0519)"
4,201362142,2901,220003839,01/28/2022 07:11:29 PM,2022-01-28 14:40:00,01/28/2022 02:46:00 PM,290,1,Crime Against Property,Destruction/Damage/Vandalism of Property,...,545,18500.0,N,FREDERICK,NaN,AVE,39.16059,-77.2209,6D,"(39.1606, -77.2209)"

In [4]:
dfCrime = dfCrime.loc[(dfCrime['Start_Date_Time'] >= '2017-01-01') & (dfCrime['Start_Date_Time'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(163444, 30)

,Incident ID,Offence Code,CR Number,Dispatch Date / Time,Start_Date_Time,End_Date_Time,NIBRS Code,Victims,Crime Name1,Crime Name2,...,PRA,Address Number,Street Prefix,Street Name,Street Suffix,Street Type,Latitude,Longitude,Police District Number,Location
0,201166610,2308,170548599,NaN,2017-12-14 16:30:00,NaN,23D,1,Crime Against Property,Theft from Building,...,270,1700.0,E,JEFFERSON,NaN,ST,39.05848,-77.1264,1D,"(39.0585, -77.1264)"
10,201225360,2204,190004807,01/30/2019 07:49:25 PM,2019-01-30 19:49:00,NaN,220,1,Crime Against Property,Burglary/Breaking and Entering,...,145,11500.0,NaN,LOCKWOOD,NaN,DR,39.04120,-76.9862,3D,"(39.0412, -76.9862)"
14,201120396,1313,17007461,NaN,2017-02-11 07:19:00,NaN,13B,1,Crime Against Person,Simple Assault,...,372,1.0,NaN,CARONA,NaN,CT,39.10084,-77.0225,4D,"(39.1008, -77.0225)"
15,201120396,2902,17007461,NaN,2017-02-11 07:19:00,NaN,290,1,Crime Against Property,Destruction/Damage/Vandalism of Property,...,372,1.0,NaN,CARONA,NaN,CT,39.10084,-77.0225,4D,"(39.1008, -77.0225)"
16,201127168,3582,17014976,NaN,2017-03-23 23:33:00,NaN,35A,1,Crime Against Society,Drug/Narcotic Violations,...,168,10100.0,NaN,GEORGIA,NaN,AVE,0.00000,0.0000,3D,"(0.0, 0.0)"

In [6]:
list(dfCrime['Crime Name2'].unique())

['Theft from Building',
 'Burglary/Breaking and Entering',
 'Simple Assault',
 'Destruction/Damage/Vandalism of Property',
 'Drug/Narcotic Violations',
 'Statuory Rape',
 'Aggravated Assault',
 'Shoplifting',
 'All other Larceny',
 'Weapon Law Violations',
 'Driving Under the Influence',
 'Robbery',
 'Extortion/Blackmail',
 'Trespass of Real Property',
 'Drug Equipment Violations',
 'Theft From Motor Vehicle',
 'Liquor Law Violations',
 'Disorderly Conduct',
 'Theft of Motor Vehicle Parts or Accessories',
 'Pocket/picking',
 'Identity Theft',
 'Forcible Rape',
 'Prostitution',
 'Assisting or Promoting Prostitution',
 'Forcible Fondling',
 'Counterfeiting/Forgery',
 'False Pretenses/Swindle/Confidence Game',
 'Stolen Property Offenses',
 'Family Offenses, NonViolent',
 'All Other Offenses',
 'Arson',
 'Credit Card/Automatic Teller Machine Fraud',
 'Impersonation',
 'Motor Vehicle Theft',
 'Wire Fraud',
 'Intimidation',
 'Purse-snatching',
 'Pornography/Obscene Material',
 'Human Trafficking, Commercial Sex Acts',
 'Embezzlement',
 'Murder and Nonnegligent Manslaughter',
 'Kidnapping/Abduction',
 'Animal Cruelty',
 'From Coin/Operated Machine or Device',
 'Curfew/Loitering/Vagrancy Violations',
 'Incest',
 'Negligent Manslaughter',
 'Operating/Promoting/Assisting Gambling',
 'Welfare Fraud',
 'Runaway',
 'Justifiable Homicide']

In [7]:
violentCrimes = ['Robbery', 'Aggravated Assault', 'Forcible Rape', 'Murder and Nonnegligent Manslaughter', 'Human Trafficking, Commercial Sex Acts']
propertyCrimes = ['Burglary/Breaking and Entering', 'Theft From Motor Vehicle', 'Theft from Building', 'All other Larceny', 
                  'Stolen Property Offenses', 'Theft of Motor Vehicle Parts or Accessories', 'Motor Vehicle Theft']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['Crime Name2'].isin(both)]
dfCrime = dfCrime[['Crime Name2', 'Longitude', 'Latitude']]
print(dfCrime.shape)
dfCrime.head()

(41418, 3)

                       Crime Name2  Longitude  Latitude
0              Theft from Building   -77.1264  39.05848
10  Burglary/Breaking and Entering   -76.9862  39.04120
19  Burglary/Breaking and Entering   -77.1566  39.04760
26              Aggravated Assault   -77.0798  39.08857
27             Theft from Building   -77.0519  39.03758

In [8]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Crime Name2', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(41418, 2)

                       Crime Name2                             geometry
0              Theft from Building            POINT (-77.1264 39.05848)
10  Burglary/Breaking and Entering             POINT (-76.9862 39.0412)
19  Burglary/Breaking and Entering             POINT (-77.1566 39.0476)
26              Aggravated Assault  POINT (-77.07980000000001 39.08857)
27             Theft from Building            POINT (-77.0519 39.03758)

In [9]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_24_bg_500k/cb_2018_24_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(3916, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,24,047,980000,1,1500000US240479800001,240479800001,1,BG,36014136,196706380,"POLYGON ((-75.379 38.025, -75.378 38.026, -75...."
1,24,019,970900,2,1500000US240199709002,240199709002,2,BG,264765218,196678699,"MULTIPOLYGON (((-76.065 38.13, -76.065 38.13, ..."
2,24,003,706302,3,1500000US240037063023,240037063023,3,BG,500847,785990,"POLYGON ((-76.486 38.973, -76.481 38.977, -76...."
3,24,027,606606,1,1500000US240276066061,240276066061,1,BG,709671,0,"POLYGON ((-76.823 39.213, -76.822 39.213, -76...."
4,24,005,491201,1,1500000US240054912011,240054912011,1,BG,1126592,0,"POLYGON ((-76.588 39.402, -76.585 39.402, -76...."

In [10]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                       Crime Name2                geometry
0              Theft from Building  POINT (-77.126 39.058)
10  Burglary/Breaking and Entering  POINT (-76.986 39.041)
19  Burglary/Breaking and Entering  POINT (-77.157 39.048)
26              Aggravated Assault   POINT (-77.08 39.089)
27             Theft from Building  POINT (-77.052 39.038)

In [11]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(41418, 13)

,Crime Name2,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
0,Theft from Building,POINT (-77.126 39.058),771.0,24,031,701218,3,1500000US240317012183,240317012183,3,BG,448951.0,0.0
10,Burglary/Breaking and Entering,POINT (-76.986 39.041),709.0,24,031,701509,3,1500000US240317015093,240317015093,3,BG,271849.0,0.0
19,Burglary/Breaking and Entering,POINT (-77.157 39.048),1535.0,24,031,701206,1,1500000US240317012061,240317012061,1,BG,1982977.0,7494.0
26,Aggravated Assault,POINT (-77.08 39.089),1776.0,24,031,703201,1,1500000US240317032011,240317032011,1,BG,1466179.0,0.0
27,Theft from Building,POINT (-77.052 39.038),1510.0,24,031,703800,1,1500000US240317038001,240317038001,1,BG,1215015.0,210.0

In [12]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US240317038001    353.333333
1500000US240317025001    283.333333
1500000US240317025004    172.333333
1500000US240317003092    133.333333
1500000US240317007132    131.000000
                            ...
1500000US240317032181      1.000000
1500000US240317053002      1.000000
1500000US240317032191      1.000000
1500000US240338073052      0.666667
1500000US240338059061      0.333333
Name: count, Length: 614, dtype: float64

In [14]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/MontMD_all_crime_by_BG.csv')

In [15]:
result2 = result[result['Crime Name2'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US240317038001    66.000000
1500000US240317007132    37.000000
1500000US240317025001    30.666667
1500000US240317003092    27.666667
1500000US240317025004    27.333333
                           ...
1500000US240317044012     0.333333
1500000US240317012102     0.333333
1500000US240317057011     0.333333
1500000US240317044041     0.333333
1500000US240317014151     0.333333
Name: count, Length: 538, dtype: float64

In [16]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/MontMD_violent_crime_by_BG.csv')

In [17]:
result3 = result[result['Crime Name2'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US240317038001    287.333333
1500000US240317025001    252.666667
1500000US240317025004    145.000000
1500000US240317060122    109.333333
1500000US240317009041    108.333333
                            ...
1500000US240317032191      1.000000
1500000US240317032181      0.666667
1500000US240317053002      0.666667
1500000US240338073052      0.666667
1500000US240338059061      0.333333
Name: count, Length: 614, dtype: float64

In [18]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/MontMD_property_crime_by_BG.csv')

In [19]:
result4 = result[result['Crime Name2'].isin(['Motor Vehicle Theft'])]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US240317025001    21.000000
1500000US240317038001    15.000000
1500000US240317024023    13.000000
1500000US240317014221    10.666667
1500000US240317014211     9.666667
                           ...
1500000US240317009051     0.333333
1500000US240317010061     0.333333
1500000US240317015082     0.333333
1500000US240317060071     0.333333
1500000US240317013031     0.333333
Name: count, Length: 515, dtype: float64

In [20]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/MontMD_mv_crime_by_BG.csv')