In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Police_Department_Incident_Reports__2018_to_Present_20250412.csv')
temp = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Police_Department_Incident_Reports__Historical_2003_to_May_2018_20250430.csv')
dfCrime = pd.concat([dfCrime, temp])
print(dfCrime.shape)
dfCrime.head()

(3077435, 68)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Fix It Zones as of 2017-11-06 2 2,DELETE - HSOC Zones 2 2,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2
0,2023/03/01 05:02:00 AM,2023/03/01,05:02,2023.0,Wednesday,2023/03/11 03:40:00 PM,1.253795e+11,1253795.0,236046151.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2023/03/13 10:59:00 AM,2023/03/13,10:59,2023.0,Monday,2023/03/13 11:00:00 AM,1.253551e+11,1253551.0,230174885.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2023/03/14 06:44:00 PM,2023/03/14,18:44,2023.0,Tuesday,2023/03/14 06:45:00 PM,1.254024e+11,1254024.0,230176728.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2023/02/15 03:00:00 AM,2023/02/15,03:00,2023.0,Wednesday,2023/03/11 04:55:00 PM,1.253786e+11,1253786.0,236046123.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2023/03/11 03:00:00 PM,2023/03/11,15:00,2023.0,Saturday,2023/03/13 08:29:00 AM,1.254206e+11,1254206.0,236045937.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
dfCrime = dfCrime[(dfCrime['Latitude'].isna() == False) & (dfCrime['Longitude'].isna() == False)]
print(dfCrime.shape)
dfCrime.head()

(896213, 68)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Fix It Zones as of 2017-11-06 2 2,DELETE - HSOC Zones 2 2,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2
6,2022/06/27 12:00:00 PM,2022/06/27,12:00,2022.0,Monday,2023/03/15 05:20:00 PM,1.254394e+11,1254393.0,230184129.0,230742480.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,2023/03/16 05:30:00 PM,2023/03/16,17:30,2023.0,Thursday,2023/03/16 06:02:00 PM,1.254826e+11,1254826.0,230187101.0,230752550.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,2023/03/21 03:50:00 PM,2023/03/21,15:50,2023.0,Tuesday,2023/03/21 04:01:00 PM,1.256564e+11,1256563.0,230199764.0,230802198.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
144,2021/07/03 12:00:00 PM,2021/07/03,12:00,2021.0,Saturday,2021/07/03 12:37:00 PM,1.046245e+11,1046244.0,210417332.0,211841413.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
145,2021/07/22 07:16:00 PM,2021/07/22,19:16,2021.0,Thursday,2021/07/23 01:35:00 PM,1.053416e+11,1053415.0,216098495.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
dfCrime = dfCrime[dfCrime['Incident Year'].isin([2019, 2018, 2017])]
print(dfCrime.shape)
dfCrime.head()

(282061, 68)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Fix It Zones as of 2017-11-06 2 2,DELETE - HSOC Zones 2 2,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2
200,2019/06/11 04:30:00 PM,2019/06/11,16:30,2019.0,Tuesday,2021/06/05 05:17:00 AM,1.037700e+11,1037700.0,210348157.0,211560467.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
790,2019/06/01 12:00:00 AM,2019/06/01,00:00,2019.0,Saturday,2022/03/29 10:45:00 AM,1.135367e+11,1135366.0,220204947.0,220881074.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1533,2018/12/01 12:00:00 PM,2018/12/01,12:00,2018.0,Saturday,2025/03/19 04:20:00 PM,1.469998e+11,1469998.0,180951860.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1990,2018/11/10 03:00:00 PM,2018/11/10,15:00,2018.0,Saturday,2025/03/26 03:16:00 PM,1.471689e+11,1471688.0,250170885.0,250852094.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3021,2018/03/07 07:00:00 AM,2018/03/07,07:00,2018.0,Wednesday,2023/08/24 05:33:00 AM,1.312400e+11,1312400.0,190202001.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
list(dfCrime['Incident Subcategory'].unique())

['Rape',
 'Courtesy Report',
 'Fraud',
 'Miscellaneous Investigation',
 'Larceny Theft - Other',
 'Lost Property',
 'Motor Vehicle Theft',
 'Missing Adult',
 'Simple Assault',
 'Case Closure',
 'Non-Criminal',
 'Suspicious Occ',
 'Other',
 'Larceny - From Vehicle',
 'Larceny Theft - Shoplifting',
 'Embezzlement',
 'Forgery And Counterfeiting',
 'Stolen Property',
 'Robbery - Other',
 'Larceny Theft - From Building',
 'Aggravated Assault',
 'Sex Offense',
 'Vandalism',
 'Robbery - Street',
 'Recovered Vehicle',
 'Arson',
 'Trespass',
 'Theft From Vehicle',
 'Drug Violation',
 nan,
 'Missing Person',
 'Prostitution',
 'Disorderly Conduct',
 'Robbery - Commercial',
 'Intimidation',
 'Suicide',
 'Larceny Theft - Bicycle',
 'Fire Report',
 'Burglary - Commercial',
 'Vehicle Impounded',
 'Weapons Offense',
 'Stalking',
 'Burglary - Residential',
 'Traffic Violation Arrest',
 'Warrant',
 'Manslaughter',
 'Burglary - Other',
 'Drunkenness',
 'Kidnapping',
 'Other Offenses',
 'Larceny Theft - Pickpocket',
 'Traffic Collision - Hit & Run',
 'Burglary - Hot Prowl',
 'Robbery - Carjacking',
 'Loitering',
 'Motor Vehicle Theft (Attempted)',
 'Larceny Theft - Purse Snatch',
 'Larceny - Auto Parts',
 'Extortion-Blackmail',
 'Human Trafficking, Commercial Sex Acts',
 'Liquor Law Violation',
 'Traffic Collision',
 'Vehicle Misplaced',
 'Suspicious Package',
 'Gambling',
 'Rape - Attempted',
 'Bad Checks',
 'Robbery - Residential',
 'Bribery',
 'Homicide',
 'Arrest',
 'Human Trafficking, Involuntary Servitude']

In [7]:
violentCrimes = ['Aggravated Assault', 'Rape - Attempted', 'Robbery - Residential', 'Robbery - Street', 'Robbery - Carjacking',
                'Sex Offense', 'Robbery - Commercial', 'Rape', 'Homicide', 'Robbery - Other']
propertyCrimes = ['Motor Vehicle Theft', 'Larceny Theft - Other', 'Larceny - From Vehicle', 'Larceny Theft - Shoplifting',
                  'Larceny Theft - From Building', 'Theft From Vehicle', 'Burglary - Commercial', 'Burglary - Residential',
                  'Burglary - Other', 'Larceny Theft - Pickpocket', 'Burglary - Hot Prowl', 'Larceny Theft - Bicycle', 
                  'Larceny - Auto Parts', 'Larceny Theft - Purse Snatch', 'Motor Vehicle Theft (Attempted)']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['Incident Subcategory'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(125406, 68)

,Incident Datetime,Incident Date,Incident Time,Incident Year,Incident Day of Week,Report Datetime,Row ID,Incident ID,Incident Number,CAD Number,...,Fix It Zones as of 2017-11-06 2 2,DELETE - HSOC Zones 2 2,Fix It Zones as of 2018-02-07 2 2,"CBD, BID and GBD Boundaries as of 2017 2 2","Areas of Vulnerability, 2016 2 2",Central Market/Tenderloin Boundary 2 2,Central Market/Tenderloin Boundary Polygon - Updated 2 2,HSOC Zones as of 2018-06-05 2 2,OWED Public Spaces 2 2,Neighborhoods 2
200,2019/06/11 04:30:00 PM,2019/06/11,16:30,2019.0,Tuesday,2021/06/05 05:17:00 AM,1.037700e+11,1037700.0,210348157.0,211560467.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3021,2018/03/07 07:00:00 AM,2018/03/07,07:00,2018.0,Wednesday,2023/08/24 05:33:00 AM,1.312400e+11,1312400.0,190202001.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3071,2018/03/07 07:00:00 AM,2018/03/07,07:00,2018.0,Wednesday,2023/08/24 06:37:00 PM,1.312401e+11,1312401.0,190202001.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6261,2019/07/26 08:00:00 AM,2019/07/26,08:00,2019.0,Friday,2023/08/31 01:50:00 PM,1.313475e+11,1313475.0,230622395.0,232430739.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6428,2019/02/06 06:00:00 PM,2019/02/06,18:00,2019.0,Wednesday,2023/02/10 03:32:00 PM,1.259824e+11,1259824.0,236024323.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
dfCrime = dfCrime[['Incident Subcategory', 'Longitude', 'Latitude']]
dfCrime.head()

       Incident Subcategory   Longitude   Latitude
200                    Rape -122.408846  37.775953
3021  Larceny Theft - Other -122.410731  37.768178
3071  Larceny Theft - Other -122.410731  37.768178
6261    Motor Vehicle Theft -122.404306  37.742521
6428  Larceny Theft - Other -122.416401  37.777723

In [9]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident Subcategory', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(125406, 2)

       Incident Subcategory                                      geometry
200                    Rape  POINT (-122.4088457506342 37.77595322850279)
3021  Larceny Theft - Other  POINT (-122.4107307185833 37.76817786907554)
3071  Larceny Theft - Other  POINT (-122.4107307185833 37.76817786907554)
6261    Motor Vehicle Theft    POINT (-122.40430629342 37.74252073319404)
6428  Larceny Theft - Other  POINT (-122.4164010718398 37.77772275002857)

In [10]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_06_bg_500k/cb_2018_06_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(23196, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,06,075,980401,1,1500000US060759804011,060759804011,1,BG,419323,247501289,"POLYGON ((-123.01 37.7, -123.01 37.699, -123.0..."
1,06,059,062702,1,1500000US060590627021,060590627021,1,BG,513205,635569,"POLYGON ((-117.88 33.593, -117.88 33.595, -117..."
2,06,037,576602,1,1500000US060375766021,060375766021,1,BG,246841,1907927,"MULTIPOLYGON (((-118.18 33.765, -118.17 33.765..."
3,06,075,061500,6,1500000US060750615006,060750615006,6,BG,313325,229501,"POLYGON ((-122.39 37.783, -122.39 37.787, -122..."
4,06,049,000300,2,1500000US060490003002,060490003002,2,BG,1781768492,310119189,"POLYGON ((-120.82 41.994, -120.79 41.994, -120..."

In [11]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       Incident Subcategory                geometry
200                    Rape  POINT (-122.41 37.776)
3021  Larceny Theft - Other  POINT (-122.41 37.768)
3071  Larceny Theft - Other  POINT (-122.41 37.768)
6261    Motor Vehicle Theft   POINT (-122.4 37.743)
6428  Larceny Theft - Other  POINT (-122.42 37.778)

In [12]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(125406, 13)

,Incident Subcategory,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
200,Rape,POINT (-122.41 37.776),11436.0,06,075,017802,1,1500000US060750178021,060750178021,1,BG,320288.0,0.0
3021,Larceny Theft - Other,POINT (-122.41 37.768),20625.0,06,075,017700,1,1500000US060750177001,060750177001,1,BG,451236.0,0.0
3071,Larceny Theft - Other,POINT (-122.41 37.768),20625.0,06,075,017700,1,1500000US060750177001,060750177001,1,BG,451236.0,0.0
6261,Motor Vehicle Theft,POINT (-122.4 37.743),15447.0,06,075,980900,1,1500000US060759809001,060759809001,1,BG,3585240.0,260707.0
6428,Larceny Theft - Other,POINT (-122.42 37.778),19117.0,06,075,012402,2,1500000US060750124022,060750124022,2,BG,196307.0,0.0

In [13]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US060750117002    1592.666667
1500000US060750615001    1125.333333
1500000US060750101001     954.333333
1500000US060750102001     675.000000
1500000US060750105002     583.000000
                            ...
1500000US060750352011       3.000000
1500000US060816009001       2.333333
1500000US060816004012       2.000000
1500000US060816007001       1.000000
1500000US060750426021       0.333333
Name: count, Length: 583, dtype: float64

In [14]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_All_Crime_BG.csv')

In [15]:
result2 = result[result['Incident Subcategory'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US060750117002    151.333333
1500000US060750615001    138.000000
1500000US060750176015    116.000000
1500000US060750125012     94.333333
1500000US060750176013     86.333333
                            ...
1500000US060750215004      0.333333
1500000US060750303022      0.333333
1500000US060750476003      0.333333
1500000US060750428001      0.333333
1500000US060750329013      0.333333
Name: count, Length: 535, dtype: float64

In [16]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_Violent_Crime_BG.csv')

In [17]:
result3 = result[result['Incident Subcategory'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US060750117002    1441.333333
1500000US060750615001     987.333333
1500000US060750101001     918.333333
1500000US060750102001     656.333333
1500000US060759803001     547.333333
                            ...
1500000US060816002001       3.000000
1500000US060816009001       2.000000
1500000US060816004012       2.000000
1500000US060816007001       1.000000
1500000US060750426021       0.333333
Name: count, Length: 583, dtype: float64

In [18]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_Property_Crime_BG.csv')

In [19]:
result4 = result[result['Incident Subcategory'].isin(['Motor Vehicle Theft', 'Motor Vehicle Theft (Attempted)'])]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US060759809001    85.333333
1500000US060750180002    60.333333
1500000US060750177001    40.666667
1500000US060750615001    40.333333
1500000US060759803001    36.333333
                           ...
1500000US060750477022     0.333333
1500000US060750113002     0.333333
1500000US060750128004     0.333333
1500000US060750327005     0.333333
1500000US060750426011     0.333333
Name: count, Length: 578, dtype: float64

In [20]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/SF_MV_Crime_BG.csv')