In [26]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [28]:
dfCrime = pd.read_csv('/Users/austincoffelt/Downloads/Crime_Reports_20250418.csv')
print(dfCrime.shape)
dfCrime.head()

(102415, 7)

,File Number,Date of Report,Crime Date Time,Crime,Reporting Area,Neighborhood,Location
0,2009-00513,01/21/2009 10:19:00 AM,01/21/2009 10:19,Warrant Arrest,108.0,East Cambridge,"100 Sixth St, Cambridge, MA"
1,2009-00515,01/21/2009 02:26:00 PM,01/05/2009 09:00 - 01/21/2009 12:00,Flim Flam,105.0,East Cambridge,"100 Sciarappa St, Cambridge, MA"
2,2009-00516,01/21/2009 02:48:00 PM,10/01/2008 00:00 - 01/21/2009 00:00,Forgery,105.0,East Cambridge,"300 Charles St, Cambridge, MA"
3,2009-00531,01/21/2009 09:11:00 PM,01/21/2009 19:05 - 21:00,Hit and Run,908.0,Peabody,"300 Concord Ave, Cambridge, MA"
4,2009-00542,01/22/2009 07:55:00 AM,01/22/2009 07:55,Warrant Arrest,1109.0,North Cambridge,"400 Rindge Ave, Cambridge, MA"

In [30]:
dfCrime['Date of Report'] = pd.to_datetime(dfCrime['Date of Report'])
dfCrime.head()

,File Number,Date of Report,Crime Date Time,Crime,Reporting Area,Neighborhood,Location
0,2009-00513,2009-01-21 10:19:00,01/21/2009 10:19,Warrant Arrest,108.0,East Cambridge,"100 Sixth St, Cambridge, MA"
1,2009-00515,2009-01-21 14:26:00,01/05/2009 09:00 - 01/21/2009 12:00,Flim Flam,105.0,East Cambridge,"100 Sciarappa St, Cambridge, MA"
2,2009-00516,2009-01-21 14:48:00,10/01/2008 00:00 - 01/21/2009 00:00,Forgery,105.0,East Cambridge,"300 Charles St, Cambridge, MA"
3,2009-00531,2009-01-21 21:11:00,01/21/2009 19:05 - 21:00,Hit and Run,908.0,Peabody,"300 Concord Ave, Cambridge, MA"
4,2009-00542,2009-01-22 07:55:00,01/22/2009 07:55,Warrant Arrest,1109.0,North Cambridge,"400 Rindge Ave, Cambridge, MA"

In [32]:
dfCrime = dfCrime.loc[(dfCrime['Date of Report'] >= '2017-01-01') & (dfCrime['Date of Report'] < '2020-01-01')]
dfCrime = dfCrime[dfCrime['Location'].isna() == False]
print(dfCrime.shape)
dfCrime.head()

(16796, 7)

,File Number,Date of Report,Crime Date Time,Crime,Reporting Area,Neighborhood,Location
48857,2017-00006,2017-01-01 03:46:00,01/01/2017 03:46,Street Robbery,405.0,The Port,"100 Pine St, Cambridge, MA"
48858,2017-00008,2017-01-01 10:55:00,01/01/2017 00:30 - 10:54,Larceny from MV,405.0,The Port,"100 Pine St, Cambridge, MA"
49642,2017-00699,2017-02-01 19:12:00,02/01/2017 19:10 - 19:11,Simple Assault,411.0,The Port,"600 Massachusetts Ave, Cambridge, MA"
49643,2017-00712,2017-02-02 09:00:00,02/01/2017 23:00 - 02/02/2017 08:59,Larceny from MV,405.0,The Port,"Eaton St & Pine St, Cambridge, MA"
49712,2017-00718,2017-02-02 13:57:00,02/02/2017 13:56,Hit and Run,1005.0,West Cambridge,"Acacia St & Ash St, Cambridge, MA"

In [34]:
sorted(list(dfCrime['Crime'].unique()))

['Accident',
 'Admin Error',
 'Aggravated Assault',
 'Annoying & Accosting',
 'Arson',
 'Auto Theft',
 'Commercial Break',
 'Commercial Robbery',
 'Counterfeiting',
 'Disorderly',
 'Drinking in Public',
 'Drugs',
 'Embezzlement',
 'Extortion/Blackmail',
 'Flim Flam',
 'Forgery',
 'Gambling',
 'Harassment',
 'Hit and Run',
 'Homicide',
 'Housebreak',
 'Indecent Exposure',
 'Kidnapping',
 'Larceny (Misc)',
 'Larceny from Building',
 'Larceny from MV',
 'Larceny from Person',
 'Larceny from Residence',
 'Larceny of Bicycle',
 'Larceny of Plate',
 'Larceny of Services',
 'Liquor Possession/Sale',
 'Mal. Dest. Property',
 'Missing Person',
 'Noise Complaint',
 'OUI',
 'Peeping & Spying',
 'Phone Calls',
 'Prostitution',
 'Rec. Stol. Property',
 'Sex Offender Violation',
 'Shoplifting',
 'Simple Assault',
 'Stalking',
 'Street Robbery',
 'Suspicious Package',
 'Taxi Violation',
 'Threats',
 'Trespassing',
 'Violation of H.O.',
 'Violation of R.O.',
 'Warrant Arrest',
 'Weapon Violations']

In [36]:
violentCrimes = ['Aggravated Assault', 'Commercial Robbery', 'Homicide', 'Street Robbery']
propertyCrimes = ['Auto Theft', 'Commercial Break', 'Housebreak', 'Larceny (Misc)', 'Larceny from Building',
                  'Larceny from MV', 'Larceny from Person', 'Larceny from Residence', 'Larceny of Bicycle',
                  'Larceny of Plate', 'Larceny of Services']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['Crime'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(5595, 7)

,File Number,Date of Report,Crime Date Time,Crime,Reporting Area,Neighborhood,Location
48857,2017-00006,2017-01-01 03:46:00,01/01/2017 03:46,Street Robbery,405.0,The Port,"100 Pine St, Cambridge, MA"
48858,2017-00008,2017-01-01 10:55:00,01/01/2017 00:30 - 10:54,Larceny from MV,405.0,The Port,"100 Pine St, Cambridge, MA"
49643,2017-00712,2017-02-02 09:00:00,02/01/2017 23:00 - 02/02/2017 08:59,Larceny from MV,405.0,The Port,"Eaton St & Pine St, Cambridge, MA"
49713,2017-00723,2017-02-02 15:55:00,01/26/2017 16:45 - 02/02/2017 15:55,Larceny (Misc),603.0,Mid-Cambridge,"300 Broadway, Cambridge, MA"
49715,2017-00726,2017-02-02 16:42:00,02/01/2017 16:41 - 02/02/2017 16:41,Larceny from MV,405.0,The Port,"Eaton St & Pine St, Cambridge, MA"

In [38]:
import pandas as pd
from tqdm import tqdm
import requests
import time  # You need to import time for the sleep function

def geocode_address(address, api_key):
    base_url = "https://maps.googleapis.com/maps/api/geocode/json"
    params = {
        "address": address,
        "key": api_key
    }
    
    try:
        response = requests.get(base_url, params=params)
        response.raise_for_status()  # Raises an exception for HTTP errors
        data = response.json()
        
        if data["status"] == "OK":
            location = data["results"][0]["geometry"]["location"]
            return location["lat"], location["lng"]
        else:
            print(f"Geocoding failed for {address}. Status: {data['status']}")
            return None, None
    except Exception as e:
        print(f"Error geocoding {address}: {str(e)}")
        return None, None

def geocode_dataframe(df, api_key, address_col='Location'):
    results = []
    
    for address in tqdm(df[address_col], desc="Geocoding addresses"):
        lat, lng = geocode_address(address, api_key)
        results.append({
            'address': address,
            'latitude': lat,
            'longitude': lng,
            'geocoded': lat is not None
        })
        time.sleep(0.1)  # Respect rate limits
    
    return pd.DataFrame(results)

geocoded_df = geocode_dataframe(dfCrime, '1')
print(geocoded_df.shape)
geocoded_df.head()

Geocoding addresses:  13%|██              | 713/5595 [04:14<41:51:58, 30.87s/it]

Error geocoding 400 Broadway, Cambridge, MA: HTTPSConnectionPool(host='maps.googleapis.com', port=443): Read timed out. (read timeout=None)

Geocoding addresses: 100%|██████████████████| 5595/5595 [21:56<00:00,  4.25it/s]

(5595, 4)

                             address   latitude  longitude  geocoded
0         100 Pine St, Cambridge, MA  42.365690 -71.097526      True
1         100 Pine St, Cambridge, MA  42.365690 -71.097526      True
2  Eaton St & Pine St, Cambridge, MA  42.364654 -71.098129      True
3        300 Broadway, Cambridge, MA  42.368146 -71.098466      True
4  Eaton St & Pine St, Cambridge, MA  42.364654 -71.098129      True

In [40]:
# make our lon and lat into a point type for spacial join
geocoded_df = geocoded_df[geocoded_df['geocoded']]
geocoded_df['geometry'] = geocoded_df.apply(lambda row: Point(row['longitude'], row['latitude']), axis=1)
dfCrime = geocoded_df[['address', 'geometry']]
dfCrime.head()

                             address                               geometry
0         100 Pine St, Cambridge, MA  POINT (-71.09752589999999 42.3656902)
1         100 Pine St, Cambridge, MA  POINT (-71.09752589999999 42.3656902)
2  Eaton St & Pine St, Cambridge, MA  POINT (-71.09812909999999 42.3646542)
3        300 Broadway, Cambridge, MA  POINT (-71.0984655 42.36814589999999)
4  Eaton St & Pine St, Cambridge, MA  POINT (-71.09812909999999 42.3646542)

In [42]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_25_bg_500k/cb_2018_25_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(4982, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,25,025,090901,2,1500000US250250909012,250250909012,2,BG,900600,293189,"POLYGON ((-71.051 42.321, -71.049 42.32, -71.0..."
1,25,009,203200,5,1500000US250092032005,250092032005,5,BG,814616,419184,"POLYGON ((-70.887 42.498, -70.882 42.503, -70...."
2,25,025,090700,3,1500000US250250907003,250250907003,3,BG,117677,0,"POLYGON ((-71.061 42.322, -71.061 42.322, -71...."
3,25,009,217202,3,1500000US250092172023,250092172023,3,BG,263736,59670,"POLYGON ((-70.898 42.544, -70.894 42.547, -70...."
4,25,017,339600,3,1500000US250173396003,250173396003,3,BG,134287,0,"POLYGON ((-71.115 42.402, -71.113 42.403, -71...."

In [44]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                             address                geometry
0         100 Pine St, Cambridge, MA  POINT (-71.098 42.366)
1         100 Pine St, Cambridge, MA  POINT (-71.098 42.366)
2  Eaton St & Pine St, Cambridge, MA  POINT (-71.098 42.365)
3        300 Broadway, Cambridge, MA  POINT (-71.098 42.368)
4  Eaton St & Pine St, Cambridge, MA  POINT (-71.098 42.365)

In [46]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(5594, 13)

,address,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
0,"100 Pine St, Cambridge, MA",POINT (-71.098 42.366),1152,25,017,352500,2,1500000US250173525002,250173525002,2,BG,104194,0
1,"100 Pine St, Cambridge, MA",POINT (-71.098 42.366),1152,25,017,352500,2,1500000US250173525002,250173525002,2,BG,104194,0
2,"Eaton St & Pine St, Cambridge, MA",POINT (-71.098 42.365),1570,25,017,353101,2,1500000US250173531012,250173531012,2,BG,210461,0
3,"300 Broadway, Cambridge, MA",POINT (-71.098 42.368),1152,25,017,352500,2,1500000US250173525002,250173525002,2,BG,104194,0
4,"Eaton St & Pine St, Cambridge, MA",POINT (-71.098 42.365),1570,25,017,353101,2,1500000US250173531012,250173531012,2,BG,210461,0

In [48]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US250173541004    95.000000
1500000US250173531011    89.333333
1500000US250173521021    84.666667
1500000US250173530003    81.666667
1500000US250173524002    55.333333
                           ...
1500000US250250711012     0.333333
1500000US250250801001     0.333333
1500000US250214007002     0.333333
1500000US250250203021     0.333333
1500000US250235301002     0.333333
Name: count, Length: 109, dtype: float64

In [50]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Cambridge_All_Crime_BG.csv')