In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Crime_incidents_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(320928, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,06/14/2016 01:20:00 AM,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,12/13/2016 05:00:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,07/19/2020 03:09:00 AM,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,11/17/2014 08:08:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,04/20/2015 10:22:00 AM,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [3]:
dfCrime['Incident Datetime'] = pd.to_datetime(dfCrime['Incident Datetime'])
dfCrime.head()

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
0,16-1660403,2016-06-14 01:20:00,NaN,ASSAULT,ASSAULT,Assault,1,Tuesday,E AMHERST ST & E AMHERST ST,Buffalo,...,2,2003,55,2,2005,District D,005500,36029005500,360290001102,360290170002003
1,16-3480266,2016-12-13 05:00:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,5,Tuesday,1000 Block E LOVEJOY ST,Buffalo,...,4,4001,23,4,4001,District C,002300,36029002300,360290002004,360290034004001
2,20-2010167,2020-07-19 03:09:00,NaN,ASSAULT,Buffalo Police are investigating this report o...,Assault,3,Sunday,GRIDER ST & KENSINGTON WB,Buffalo,...,NaN,NaN,NaN,NaN,NaN,NaN,UNKNOWN,UNKNOWN,UNKNOWN,UNKNOWN
3,14-3210732,2014-11-17 08:08:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,8,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007
4,15-1100268,2015-04-20 10:22:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,10,Monday,2100 Block ELMWOOD AV,Buffalo,...,2,2007,56,2,2008,District D,005600,36029005600,360290001102,360290163002007

In [4]:
dfCrime = dfCrime.loc[(dfCrime['Incident Datetime'] >= '2017-01-01') & (dfCrime['Incident Datetime'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(44546, 31)

,Case Number,Incident Datetime,Incident ID,Incident Type Primary,Incident Description,Parent Incident Type,Hour of Day,Day of Week,Address,City,...,Census Block Group,Census Block,2010 Census Tract,2010 Census Block Group,2010 Census Block,Police District,TRACTCE20,GEOID20_tract,GEOID20_blockgroup,GEOID20_block
15,17-1290784,2017-05-09 09:16:00,NaN,LARCENY/THEFT,LARCENY/THEFT,Theft,9,Tuesday,300 Block CONNECTICUT ST,Buffalo,...,1,1002,69.02,1,1002,District B,006903,36029006903,360290001101,360290001101002
21,17-1911010,2017-07-10 11:45:00,NaN,BURGLARY,BURGLARY,Breaking & Entering,11,Monday,100 Block E DELAVAN AV,Buffalo,...,1,1010,52.02,1,1007,District E,005202,36029005202,360290001101,360290036001010
32,17-2270400,2017-08-12 12:00:00,NaN,SEXUAL ABUSE,SEXUAL ABUSE,Other Sexual Offense,12,Saturday,400 Block NORFOLK AV,Buffalo,...,1,1002,41,1,1001,District E,004100,36029004100,360290001101,360290001101002
54,17-3030346,2017-10-30 02:00:00,NaN,BURGLARY,BURGLARY,Breaking & Entering,2,Monday,1 Block GRIMES ST,Buffalo,...,5,5006,24,1,1009,District C,002400,36029002400,360290007005,360290034005006
62,17-1600180,2017-06-09 06:30:00,NaN,BURGLARY,BURGLARY,Breaking & Entering,6,Friday,400 Block GRIDER ST,Buffalo,...,5,5017,34,5,5019,District E,003400,36029003400,360290007005,360290034005017

In [6]:
list(dfCrime.columns)

['Case Number',
 'Incident Datetime',
 'Incident ID',
 'Incident Type Primary',
 'Incident Description',
 'Parent Incident Type',
 'Hour of Day',
 'Day of Week',
 'Address',
 'City',
 'State',
 'Location',
 'Latitude',
 'Longitude',
 'Created At',
 'updated_at',
 'zip_code',
 'neighborhood',
 'Council District',
 'Council District 2011',
 'Census Tract',
 'Census Block Group',
 'Census Block',
 '2010 Census Tract ',
 '2010 Census Block Group',
 '2010 Census Block',
 'Police District',
 'TRACTCE20',
 'GEOID20_tract',
 'GEOID20_blockgroup',
 'GEOID20_block']

In [7]:
sorted(list(dfCrime['Parent Incident Type'].unique()))

['Assault',
 'Breaking & Entering',
 'Homicide',
 'Other Sexual Offense',
 'Robbery',
 'Sexual Assault',
 'Sexual Offense',
 'Theft',
 'Theft of Vehicle']

In [8]:
dfCrime = dfCrime[['Incident Type Primary', 'Parent Incident Type', 'Longitude', 'Latitude']]
dfCrime = dfCrime[dfCrime['Longitude'] != 'UNKNOWN']
dfCrime = dfCrime[dfCrime['Incident Type Primary'] != 'ASSAULT']
dfCrime.head()

   Incident Type Primary  Parent Incident Type Longitude Latitude
15         LARCENY/THEFT                 Theft   -78.887   42.906
21              BURGLARY   Breaking & Entering    -78.85   42.922
32          SEXUAL ABUSE  Other Sexual Offense   -78.819   42.928
54              BURGLARY   Breaking & Entering   -78.825   42.892
62              BURGLARY   Breaking & Entering   -78.829   42.918

In [9]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['Longitude'], row['Latitude']), axis=1)
dfCrime = dfCrime[['Incident Type Primary', 'Parent Incident Type', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(34116, 3)

,Incident Type Primary,Parent Incident Type,geometry
15,LARCENY/THEFT,Theft,POINT (-78.887 42.906)
21,BURGLARY,Breaking & Entering,POINT (-78.84999999999999 42.922)
32,SEXUAL ABUSE,Other Sexual Offense,POINT (-78.819 42.928)
54,BURGLARY,Breaking & Entering,POINT (-78.825 42.892)
62,BURGLARY,Breaking & Entering,POINT (-78.82899999999999 42.918)

In [10]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_36_bg_500k/cb_2018_36_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(15406, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,36,103,110401,1,1500000US361031104011,361031104011,1,BG,534139,0,"POLYGON ((-73.399 40.904, -73.394 40.904, -73...."
1,36,119,005600,1,1500000US361190056001,361190056001,1,BG,312476,180612,"POLYGON ((-73.773 40.885, -73.772 40.887, -73...."
2,36,067,011402,3,1500000US360670114023,360670114023,3,BG,45275086,887109,"POLYGON ((-76.479 43.228, -76.451 43.229, -76...."
3,36,069,051400,2,1500000US360690514002,360690514002,2,BG,46193661,0,"POLYGON ((-77.131 42.861, -77.121 42.861, -77...."
4,36,061,018600,2,1500000US360610186002,360610186002,2,BG,48762,0,"POLYGON ((-73.952 40.799, -73.95 40.799, -73.9..."

In [11]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

   Incident Type Primary  Parent Incident Type                geometry
15         LARCENY/THEFT                 Theft  POINT (-78.887 42.906)
21              BURGLARY   Breaking & Entering   POINT (-78.85 42.922)
32          SEXUAL ABUSE  Other Sexual Offense  POINT (-78.819 42.928)
54              BURGLARY   Breaking & Entering  POINT (-78.825 42.892)
62              BURGLARY   Breaking & Entering  POINT (-78.829 42.918)

In [13]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(34116, 14)

,Incident Type Primary,Parent Incident Type,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
15,LARCENY/THEFT,Theft,POINT (-78.887 42.906),4295.0,36,029,006902,1,1500000US360290069021,360290069021,1,BG,262280.0,0.0
21,BURGLARY,Breaking & Entering,POINT (-78.85 42.922),12036.0,36,029,003301,1,1500000US360290033011,360290033011,1,BG,147038.0,0.0
32,SEXUAL ABUSE,Other Sexual Offense,POINT (-78.819 42.928),1479.0,36,029,004100,1,1500000US360290041001,360290041001,1,BG,314417.0,0.0
54,BURGLARY,Breaking & Entering,POINT (-78.825 42.892),2605.0,36,029,002400,1,1500000US360290024001,360290024001,1,BG,368396.0,0.0
62,BURGLARY,Breaking & Entering,POINT (-78.829 42.918),407.0,36,029,003400,2,1500000US360290034002,360290034002,2,BG,182280.0,0.0

In [14]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US360290165001    483.666667
1500000US360290050003    255.333333
1500000US360290050001    142.333333
1500000US360290071021    117.333333
1500000US360290164001    115.666667
                            ...
1500000US360290084002      0.666667
1500000US360290095011      0.666667
1500000US360290088003      0.666667
1500000US360290080023      0.333333
1500000US360290080033      0.333333
Name: count, Length: 301, dtype: float64

In [15]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_All_Crime_BG.csv')

In [16]:
violentCrimes = ['AGGR ASSAULT', 'RAPE', 'MURDER', 'SEXUAL ABUSE', 'ROBBERY']
result2 = result[result['Incident Type Primary'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US360290165001    47.666667
1500000US360290034002    20.000000
1500000US360290168004    14.000000
1500000US360290036003    13.000000
1500000US360290035004    11.666667
                           ...
1500000US360290093013     0.333333
1500000US360290171004     0.333333
1500000US360290009003     0.333333
1500000US360290065012     0.333333
1500000US360290007004     0.333333
Name: count, Length: 290, dtype: float64

In [22]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_Violent_Crime_BG.csv')

In [24]:
propCrimes = ['BURGLARY', 'LARCENY/THEFT', 'THEFT OF SERVICES', 'UUV']
result3 = result[result['Incident Type Primary'].isin(propCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US360290165001    435.666667
1500000US360290050003    248.666667
1500000US360290050001    134.666667
1500000US360290071021    106.666667
1500000US360290164001    106.666667
                            ...
1500000US360290084002      0.666667
1500000US360290095011      0.666667
1500000US360290080023      0.333333
1500000US360290088003      0.333333
1500000US360290080033      0.333333
Name: count, Length: 301, dtype: float64

In [33]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_Property_Crime_BG.csv')

In [35]:
propCrimes = ['Theft of Vehicle']
result4 = result[result['Parent Incident Type'].isin(propCrimes)]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US360290165001    30.000000
1500000US360290044022    12.333333
1500000US360290035001    11.666667
1500000US360290068002    11.333333
1500000US360290044021    10.000000
                           ...
1500000US360290046013     0.333333
1500000US360290007004     0.333333
1500000US360290007002     0.333333
1500000US360290167002     0.333333
1500000US360290062011     0.333333
Name: count, Length: 288, dtype: float64

In [37]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Buffalo_MV_Crime_BG.csv')