In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Incident_20250422.csv')
print(dfCrime.shape)
dfCrime.head()

(39718, 43)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_8553/3275636319.py:1: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Incident_20250422.csv')

,Case Number,Police Agency Code,Offense,Date/Time Reported,Hour Reported,Date/Time Occurred,Hour Occurred,Date/Time Found,Hour Found,Street Number,...,Location Code,Location Description,Forcible,Weapon Code,Weapon Description,Incident Disposition Code,Incident Disposition Descr.,location,Beats,Neighborhoods
0,2019004076,JCPD,IDENTITY THEFT,09/17/2019 10:29:00 AM,1029,09/12/2019 08:00:00 AM,800.0,09/17/2019 10:29:00 AM,1029.0,52XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0121231079102, -84.2033233642578)",5.0,60.0
1,2025000666,JCPD,TRAFFIC ARREST,02/16/2025 12:05:00 PM,1205,02/16/2025 12:04:59 PM,1204.0,02/16/2025 12:05:00 PM,1205.0,95XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0115814208984, -84.2828598022461)",NaN,NaN
2,2024000775,JCPD,LARCENY - SHOPLIFTING,02/22/2024 06:22:00 PM,1822,02/10/2024 02:11:59 PM,1411.0,02/22/2024 06:22:00 PM,1822.0,59XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0121078491211, -84.1879119873047)",3.0,NaN
3,2010001436,JCPD,HIT AND RUN,04/20/2010 09:05:31 AM,905,02/16/2010 09:20:00 AM,920.0,02/16/2010 11:45:00 AM,1145.0,111XX,...,18.0,PARKING LOT /GARAGE,N,N,NONE,NaN,NaN,"(29.802906036377, -91.3952789306641)",NaN,NaN
4,2022000970,JCPD,IDENTITY THEFT,03/04/2022 02:08:00 PM,1408,02/18/2022 12:00:00 PM,1200.0,02/18/2022 12:00:00 PM,1200.0,61XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0386390686035, -84.1784057617188)",3.0,NaN

In [3]:
list(dfCrime.columns)

['Case Number',
 'Police Agency Code',
 'Offense',
 'Date/Time Reported',
 'Hour Reported',
 'Date/Time Occurred',
 'Hour Occurred',
 'Date/Time Found',
 'Hour Found',
 'Street Number',
 'Street Direction',
 'Street Name',
 'Apartment/Floor',
 'city',
 'state',
 'zip',
 'geox',
 'geoy',
 'Reported As',
 'Tract Code',
 'Tract Description',
 'Zone Code',
 'Zone Description',
 'District Code',
 'District Description',
 'Reporting Area Code',
 'Reporting Area Description',
 'Neighborhood Code',
 'Neighborhood Description',
 'Subdivision Code',
 'Subdivision Description',
 'Weather Code',
 'Weather Description',
 'Location Code',
 'Location Description',
 'Forcible',
 'Weapon Code',
 'Weapon Description',
 'Incident Disposition Code',
 'Incident Disposition Descr.',
 'location',
 'Beats',
 'Neighborhoods']

In [4]:
dfCrime['Date/Time Occurred'] = pd.to_datetime(dfCrime['Date/Time Occurred'])
dfCrime.head()

,Case Number,Police Agency Code,Offense,Date/Time Reported,Hour Reported,Date/Time Occurred,Hour Occurred,Date/Time Found,Hour Found,Street Number,...,Location Code,Location Description,Forcible,Weapon Code,Weapon Description,Incident Disposition Code,Incident Disposition Descr.,location,Beats,Neighborhoods
0,2019004076,JCPD,IDENTITY THEFT,09/17/2019 10:29:00 AM,1029,2019-09-12 08:00:00,800.0,09/17/2019 10:29:00 AM,1029.0,52XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0121231079102, -84.2033233642578)",5.0,60.0
1,2025000666,JCPD,TRAFFIC ARREST,02/16/2025 12:05:00 PM,1205,2025-02-16 12:04:59,1204.0,02/16/2025 12:05:00 PM,1205.0,95XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0115814208984, -84.2828598022461)",NaN,NaN
2,2024000775,JCPD,LARCENY - SHOPLIFTING,02/22/2024 06:22:00 PM,1822,2024-02-10 14:11:59,1411.0,02/22/2024 06:22:00 PM,1822.0,59XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0121078491211, -84.1879119873047)",3.0,NaN
3,2010001436,JCPD,HIT AND RUN,04/20/2010 09:05:31 AM,905,2010-02-16 09:20:00,920.0,02/16/2010 11:45:00 AM,1145.0,111XX,...,18.0,PARKING LOT /GARAGE,N,N,NONE,NaN,NaN,"(29.802906036377, -91.3952789306641)",NaN,NaN
4,2022000970,JCPD,IDENTITY THEFT,03/04/2022 02:08:00 PM,1408,2022-02-18 12:00:00,1200.0,02/18/2022 12:00:00 PM,1200.0,61XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0386390686035, -84.1784057617188)",3.0,NaN

In [6]:
dfCrime = dfCrime.loc[(dfCrime['Date/Time Occurred'] >= '2017-01-01') & (dfCrime['Date/Time Occurred'] < '2020-01-01')]
print(dfCrime.shape)
dfCrime.head()

(8850, 43)

,Case Number,Police Agency Code,Offense,Date/Time Reported,Hour Reported,Date/Time Occurred,Hour Occurred,Date/Time Found,Hour Found,Street Number,...,Location Code,Location Description,Forcible,Weapon Code,Weapon Description,Incident Disposition Code,Incident Disposition Descr.,location,Beats,Neighborhoods
0,2019004076,JCPD,IDENTITY THEFT,09/17/2019 10:29:00 AM,1029,2019-09-12 08:00:00,800.0,09/17/2019 10:29:00 AM,1029.0,52XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0121231079102, -84.2033233642578)",5.0,60.0
13,2019004547,JCPD,PERSON DEAD,10/15/2019 04:26:55 PM,1626,2019-10-15 16:26:54,1626.0,10/15/2019 04:26:55 PM,1626.0,20XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(33.9990653991699, -84.2744522094727)",NaN,NaN
25,2017002733,JCPD,COUNTERFEITING OF -(OBJECT),06/29/2017 04:56:36 PM,1656,2017-06-24 19:00:00,1900.0,06/24/2017 07:00:00 PM,1900.0,109XX,...,21.0,RESTAURANT,N,N,NONE,NaN,NaN,"(34.0456581115723, -84.2256774902344)",5.0,168.0
28,2020000409,JCPD,FRAUD - IMPERSONATION,01/27/2020 09:30:00 AM,930,2019-12-16 00:00:00,0.0,12/16/2019 12:00:00 AM,0.0,3XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(33.9899063110352, -84.2644577026367)",7.0,NaN
62,2019004975,JCPD,IDENTITY THEFT,11/12/2019 09:25:00 AM,925,2019-08-30 09:25:00,925.0,11/12/2019 09:25:00 AM,925.0,2XX,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"(34.0574569702148, -84.2019424438477)",1.0,242.0

In [9]:
sorted(list(dfCrime['Offense'].unique()))

['AGG ASSAULT/ AGG BATTERY-GUN',
 'AGGRAVATED ASSAULT - FAMILY - OTHER WEAPON',
 'AGGRAVATED ASSAULT - NONFAMILY - OTHER WEAPON',
 'AGGRAVATED STALKING',
 'AMPHETAMINE-POSSESSION OF',
 'AMPHETAMINE-WTH-INTENT',
 'ARSON - FREE TEXT/ALL OTHER',
 'ARSON - RESIDENCE',
 'BURGLARY - BANKING - TYPE INSTITUTE',
 'BURGLARY - NONRESIDENCE - FORCED ENTRY',
 'BURGLARY - NONRESIDENCE - NO FORCE ENTRY',
 'BURGLARY - OTHER',
 'BURGLARY - RESIDENCE - FORCED ENTRY',
 'BURGLARY - RESIDENCE - NO FORCED ENTRY',
 'CARRYING A PROHIBITED WEAPON',
 'CHILD NEGLECT',
 'CITY ORDINANCE VIOLATION',
 'COCAINE- WITH INTENT',
 'COCAINE-POSSESSION',
 'CONTRIBUTING TO DELINQUENCY OF MINOR',
 'COUNTERFEITING OF -(OBJECT)',
 'CRIMINAL DAMAGE TO PROPERTY',
 'CRIMINAL TRESPASS',
 'CRUELTY TO ANIMALS',
 'CRUELTY TOWARD CHILD',
 'DAMAGED OR LOST CITY PROPERTY',
 'DANGEROUS DRUGS OTHER OFFENSE',
 'DEMENTED PERSON',
 'DISORDERLY CONDUCT',
 'DISORDERLY CONDUCT - CITY ORDINANCE',
 'DRIVERS LIC REQ  PRIOR LIC SURRENDERED: LOCAL LIC FORBIDDEN',
 'DRIVING UNDER THE INFLUENCE',
 'DRIVING UNDER THE INFLUENCE - ALCHOL',
 'DRIVING UNDER THE INFLUENCE - DRUGS',
 'DRIVING W/ LIC. SUSP/REV.',
 'DRIVING WITHOUT LICENSE',
 'EMBEZZLEMENT/THEFT BY CONVERSION OFFENSE FREE TEXT',
 'EMBEZZLEMENT/THEFT BY CONVERSION- FINANCIAL INSTITUTION PROP',
 'FAILURE TO APPEAR',
 'FALSE IMPRISONMENT - MINOR - NONPARENTAL',
 'FALSE IMPRISONMENT - MINOR - PARENTAL',
 'FAMILY OFF. (INTERFERE W/ CUST.; UNRULY CHILD; ETC)',
 'FIRING A WEAPON',
 'FLIGHT / ESCAPE  - OTHER',
 'FLIGHT TO AVOID PROSECUTION',
 'FORGERY - OTHER',
 'FORGERY- OF CHECK',
 'FORGERY- OF OTHER OBJECTS',
 'FRAUD - CONFIDENCE GAME',
 'FRAUD - FALSE STATEMENT',
 'FRAUD - ILLEGAL USE OF CREDIT / FTC',
 'FRAUD - IMPERSONATION',
 'FRAUD - INSUFFICIENT FUNDS CHECK',
 'FRAUD - SWINDLE',
 'FRAUD AND ABUSE - COMPUTER',
 'FRAUD BY WIRE',
 'FRAUDULENT ACTIVITY - OTHER',
 'HALLUCINOGEN-POSSESSION OF',
 'HALLUCINOGEN-SALES OF',
 'HARASSING COMMUNICATIONS',
 'HEROIN-POSSESSION OF',
 'HEROIN-SALES OF',
 'HEROIN-WITH INTENT',
 'HIT AND RUN',
 'IDENTITY THEFT',
 'INDECENT EXPOSURE',
 'INDECENT EXPOSURE TO MINOR',
 'INTERFERENCE WITH GOVERNMENT PROPERTY',
 'INVASION OF PRIVACY - OTHER OFFENSE',
 'LARCENY - BICYCLE',
 'LARCENY - FROM BUILDING',
 'LARCENY - FROM MAIL',
 'LARCENY - FROM RESIDENTIAL MAILBOX',
 'LARCENY - FROM VEHICLE',
 'LARCENY - FROM YARDS',
 'LARCENY - OTHER OFFENSES',
 'LARCENY - PARTS FROM VEHICLE',
 'LARCENY - POCKET PICKING',
 'LARCENY - PURSE SNATCHING - NO FORCE',
 'LARCENY - SHOPLIFTING',
 'LIQ LAW VIOL - OTHER (UN/ AGE DRINK  ETC)',
 'LOITERING AND PROWLING',
 'LOST & MISLAID PROPERTY',
 'MAKING FALSE REPORT / FALSE INFO',
 'MARIJUANA - MANUFACTURING',
 'MARIJUANA POSS OF',
 'MARIJUANA- WITH INTENT',
 'MARIJUANA-POSSESS LESS THAN 1 OZ',
 'MARIJUANA-SALES OF',
 'MISCELLANEOUS REPORT',
 'MISSING PERSON',
 'OBSCENE MATERIAL - DISTRIBUTE',
 'OBSCENE MATERIAL - POSSESS',
 'OBSCENITY OFFENSES - OTHER',
 'OBSTRUCTING JUDICIARY - OTHER',
 'OBSTRUCTING JUSTICE',
 'OBSTRUCTING OFFICER / CRIIMINAL INV.',
 'OPIUM OR DERIVATIVE - FREE TEXT',
 'OPIUM OR DERIVATIVE-POSSESSION OF',
 'PASS COUNTERFEITED OBJECT',
 'PEEPING TOM',
 'PERSON DEAD',
 'POSSESSION OF DRUG RELATED ITEMS/NARCOTIC EQUIPEMENT',
 'POSSESSION OF STOLEN PROPERTY',
 'PROBATION VIOLATION',
 'PROSTITUTION',
 'RECKLESS CONDUCT',
 'RECOVERED PROPERTY',
 'RECOVERED/FOUND PROPERTY',
 'RESISTING OFFICER / ARREST',
 'ROBBERY - OTHER',
 'ROBBERY-BANK/ FINANCIAL INSTITUTION',
 'ROBBERY-BUSINESS-GUN',
 'ROBBERY-BUSINESS-OTHER WEAPON',
 'ROBBERY-BUSINESS-STRONGARM',
 'ROBBERY-FORCIBLE PURSE SNATCHING',
 'ROBBERY-RESIDENCE-GUN',
 'ROBBERY-STREET-GUN',
 'ROBBERY-STREET-STRONGARM',
 'RUNAWAY JUVENILE',
 'SEX OFFENSE - OTHER',
 'SEXUAL ASSAULT - OTHER',
 'SIMPLE ASSAULT / BATTERY',
 'STALKING',
 'STOLEN MOTOR VEHICLE RECOVERED',
 'SUSPICIOUS ACTIVITY',
 'SYNTHETIC NARCOTIC- WITH INTENT',
 'SYNTHETIC NARCOTIC-POSSESSION OF',
 'SYNTHETIC NARCOTIC-SALES OF',
 'TERRORISTIC THREATS AND ACTS',
 'THEFT AND USE AUTOMOBILE FOR OTHER CRIME',
 'THEFT BY EXTORTION',
 'THEFT BY RECEIVING STOLEN PROPERTY',
 'THEFT BY RECEIVING STOLEN VEHICLE',
 'THEFT BY TAKING MOTOR VEHICLE',
 'THEFT OF OTHER VEHICLES',
 'THEFT OF TRUCK / BUS',
 'TRAFFIC ARREST',
 'VEHICLE FATALITY',
 'VEHICLE IMPOUND',
 'VERBAL DISPUTE',
 'VIOLATION OF A COURT ORDER',
 'WANTED PERSON LOCATED',
 'WEAPONS OFFENSES - OTHER']

In [13]:
violentCrimes = ['AGG ASSAULT/ AGG BATTERY-GUN', 'ROBBERY - OTHER', 'ROBBERY-BUSINESS-GUN', 'ROBBERY-BUSINESS-STRONGARM',
                'ROBBERY-FORCIBLE PURSE SNATCHING', 'ROBBERY-STREET-GUN', 'SEX OFFENSE - OTHER', 'SEXUAL ASSAULT - OTHER', 'PERSON DEAD']
propertyCrimes = ['BURGLARY - NONRESIDENCE - FORCED ENTRY', 'BURGLARY - NONRESIDENCE - NO FORCE ENTRY', 'BURGLARY - OTHER',
                  'BURGLARY - RESIDENCE - FORCED ENTRY', 'BURGLARY - RESIDENCE - NO FORCED ENTRY', 'LARCENY - FROM BUILDING',
                  'LARCENY - FROM MAIL', 'LARCENY - FROM RESIDENTIAL MAILBOX', 'LARCENY - FROM VEHICLE', 'LARCENY - FROM YARDS',
                  'LARCENY - OTHER OFFENSES', 'LARCENY - PARTS FROM VEHICLE', 'LARCENY - POCKET PICKING', 'LARCENY - SHOPLIFTING',
                  'THEFT AND USE AUTOMOBILE FOR OTHER CRIME', 'THEFT BY EXTORTION', 'THEFT BY RECEIVING STOLEN PROPERTY', 'THEFT BY TAKING MOTOR VEHICLE',
                  'THEFT OF OTHER VEHICLES']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['Offense'].isin(both)]
dfCrime = dfCrime[['Offense', 'geox', 'geoy']]
print(dfCrime.shape)
dfCrime.head()

(1681, 3)

                     Offense       geox       geoy
13               PERSON DEAD  33.999065 -84.274452
76   LARCENY - FROM BUILDING  34.063587 -84.164558
85   LARCENY - FROM BUILDING  34.001549 -84.259209
104      LARCENY - FROM MAIL  34.052437 -84.178436
107  LARCENY - FROM BUILDING  34.062428 -84.164116

In [15]:
# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['geoy'], row['geox']), axis=1)
dfCrime = dfCrime[['Offense', 'geometry']]
print(dfCrime.shape)
dfCrime.head()

(1681, 2)

                     Offense                                    geometry
13               PERSON DEAD  POINT (-84.2744522094727 33.9990653991699)
76   LARCENY - FROM BUILDING  POINT (-84.1645584106445 34.0635871887207)
85   LARCENY - FROM BUILDING  POINT (-84.2592086791992 34.0015487670898)
104      LARCENY - FROM MAIL  POINT (-84.1784362792969 34.0524368286133)
107  LARCENY - FROM BUILDING   POINT (-84.1641159057617 34.062427520752)

In [17]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_13_bg_500k/cb_2018_13_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(5530, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,13,121,001600,1,1500000US131210016001,131210016001,1,BG,921684,2683,"POLYGON ((-84.364 33.771, -84.359 33.771, -84...."
1,13,095,000100,3,1500000US130950001003,130950001003,3,BG,944540,0,"POLYGON ((-84.112 31.58, -84.101 31.58, -84.10..."
2,13,245,001602,3,1500000US132450016023,132450016023,3,BG,750047,0,"POLYGON ((-82.043 33.49, -82.039 33.492, -82.0..."
3,13,067,031004,2,1500000US130670310042,130670310042,2,BG,874932,8814,"POLYGON ((-84.565 33.898, -84.564 33.902, -84...."
4,13,021,012300,2,1500000US130210123002,130210123002,2,BG,505441,0,"POLYGON ((-83.67 32.844, -83.67 32.844, -83.66..."

In [19]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                     Offense                geometry
13               PERSON DEAD  POINT (-84.274 33.999)
76   LARCENY - FROM BUILDING  POINT (-84.165 34.064)
85   LARCENY - FROM BUILDING  POINT (-84.259 34.002)
104      LARCENY - FROM MAIL  POINT (-84.178 34.052)
107  LARCENY - FROM BUILDING  POINT (-84.164 34.062)

In [21]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(1681, 13)

,Offense,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
13,PERSON DEAD,POINT (-84.274 33.999),2243.0,13,121,011424,1,1500000US131210114241,131210114241,1,BG,3039783.0,2371.0
76,LARCENY - FROM BUILDING,POINT (-84.165 34.064),3747.0,13,121,011622,2,1500000US131210116222,131210116222,2,BG,8299781.0,153981.0
85,LARCENY - FROM BUILDING,POINT (-84.259 34.002),2243.0,13,121,011424,1,1500000US131210114241,131210114241,1,BG,3039783.0,2371.0
104,LARCENY - FROM MAIL,POINT (-84.178 34.052),2775.0,13,121,011626,1,1500000US131210116261,131210116261,1,BG,3926842.0,10518.0
107,LARCENY - FROM BUILDING,POINT (-84.164 34.062),3747.0,13,121,011622,2,1500000US131210116222,131210116222,2,BG,8299781.0,153981.0

In [23]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US131210116232    59.666667
1500000US131210116222    50.666667
1500000US131210116261    37.000000
1500000US131210116253    26.666667
1500000US131210116203    25.000000
1500000US131210116131    20.000000
1500000US131210116121    20.000000
1500000US131210114272    19.666667
1500000US131210114241    17.333333
1500000US131210114242    17.000000
1500000US131210116132    17.000000
1500000US131210116262    17.000000
1500000US131210114271    17.000000
1500000US131210116221    16.333333
1500000US131210116231    16.333333
1500000US131210114143    12.333333
1500000US131210114252    11.666667
1500000US131210116251    11.333333
1500000US131210116223    11.333333
1500000US131210116172    10.666667
1500000US131210116234    10.666667
1500000US131210114251    10.000000
1500000US131210114253     9.333333
1500000US131210114142     9.000000
1500000US131171306062     8.666667
1500000US131210116241     8.666667
1500000US131210116122     7.666667
1500000US131210114273     7.666667
1500000US131210116252     7.000000
1500000US131210116201     6.666667
1500000US131171306082     6.333333
1500000US131210116202     6.000000
1500000US131210114261     5.666667
1500000US131210116233     5.333333
1500000US131210116242     3.333333
1500000US131210116173     3.000000
1500000US131171306041     2.666667
1500000US131171306081     1.666667
1500000US131210114121     1.333333
1500000US131210114101     1.333333
1500000US131210116193     0.666667
1500000US131171306061     0.666667
1500000US131210114141     0.666667
1500000US131350502052     0.333333
1500000US131210114144     0.333333
1500000US131171306101     0.333333
1500000US131171306083     0.333333
Name: count, dtype: float64

In [25]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/J_Creek_All_crime_by_BG.csv')

In [27]:
result2 = result[result['Offense'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US131210116261    4.666667
1500000US131210116222    4.666667
1500000US131210116203    3.666667
1500000US131210116253    3.333333
1500000US131210116232    2.666667
1500000US131210116131    2.000000
1500000US131210116121    1.666667
1500000US131210114271    1.666667
1500000US131210116231    1.666667
1500000US131210116221    1.666667
1500000US131210114241    1.333333
1500000US131210116201    1.333333
1500000US131210114242    1.333333
1500000US131210114253    1.000000
1500000US131210116173    1.000000
1500000US131210114261    1.000000
1500000US131210116223    1.000000
1500000US131210114272    0.666667
1500000US131210114143    0.666667
1500000US131210116172    0.666667
1500000US131210116234    0.666667
1500000US131171306041    0.666667
1500000US131210114251    0.666667
1500000US131210114273    0.333333
1500000US131210116251    0.333333
1500000US131210116122    0.333333
1500000US131210116241    0.333333
1500000US131210116262    0.333333
1500000US131171306082    0.333333
Name: count, dtype: float64

In [29]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/J_Creek_violent_crime_by_BG.csv')

In [31]:
result3 = result[result['Offense'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US131210116232    57.000000
1500000US131210116222    46.000000
1500000US131210116261    32.333333
1500000US131210116253    23.333333
1500000US131210116203    21.333333
1500000US131210114272    19.000000
1500000US131210116121    18.333333
1500000US131210116131    18.000000
1500000US131210116132    17.000000
1500000US131210116262    16.666667
1500000US131210114241    16.000000
1500000US131210114242    15.666667
1500000US131210114271    15.333333
1500000US131210116231    14.666667
1500000US131210116221    14.666667
1500000US131210114252    11.666667
1500000US131210114143    11.666667
1500000US131210116251    11.000000
1500000US131210116223    10.333333
1500000US131210116172    10.000000
1500000US131210116234    10.000000
1500000US131210114251     9.333333
1500000US131210114142     9.000000
1500000US131171306062     8.666667
1500000US131210114253     8.333333
1500000US131210116241     8.333333
1500000US131210114273     7.333333
1500000US131210116122     7.333333
1500000US131210116252     7.000000
1500000US131210116202     6.000000
1500000US131171306082     6.000000
1500000US131210116233     5.333333
1500000US131210116201     5.333333
1500000US131210114261     4.666667
1500000US131210116242     3.333333
1500000US131171306041     2.000000
1500000US131210116173     2.000000
1500000US131171306081     1.666667
1500000US131210114121     1.333333
1500000US131210114101     1.333333
1500000US131210116193     0.666667
1500000US131171306061     0.666667
1500000US131210114141     0.666667
1500000US131350502052     0.333333
1500000US131210114144     0.333333
1500000US131171306101     0.333333
1500000US131171306083     0.333333
Name: count, dtype: float64

In [33]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/J_Creek_property_crime_by_BG.csv')

In [35]:
result4 = result[result['Offense'].isin(['THEFT BY TAKING MOTOR VEHICLE'])]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US131210114242    2.000000
1500000US131210116172    1.333333
1500000US131210116261    1.333333
1500000US131210116131    1.333333
1500000US131210116262    1.333333
1500000US131210116253    1.000000
1500000US131210116231    1.000000
1500000US131210116251    0.666667
1500000US131210116232    0.666667
1500000US131210114251    0.666667
1500000US131210116132    0.666667
1500000US131210114241    0.666667
1500000US131210114143    0.666667
1500000US131210114271    0.666667
1500000US131210116222    0.666667
1500000US131210114272    0.666667
1500000US131210116203    0.333333
1500000US131210114252    0.333333
1500000US131210116122    0.333333
1500000US131210116233    0.333333
1500000US131210116173    0.333333
1500000US131210116252    0.333333
1500000US131210116223    0.333333
1500000US131210116201    0.333333
1500000US131210114273    0.333333
1500000US131210114253    0.333333
Name: count, dtype: float64

In [27]:
crime.to_csv('/Users/austincoffelt/Documents/RW Data/J_Creek_mv_crime_by_BG.csv')