In [1]:
import pandas as pd
import numpy as np
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/RMS_Crime_Incidents.csv')
print(dfCrime.shape)
dfCrime.head()

(703116, 30)

/var/folders/6z/0pv81j2524v8c80qsmnrbmcm0000gn/T/ipykernel_8396/2402075416.py:1: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/RMS_Crime_Incidents.csv')

,X,Y,incident_entry_id,nearest_intersection,offense_category,offense_description,state_offense_code,arrest_charge,charge_description,incident_occurred_at,...,report_number,scout_car_area,police_precinct,census_block_2020_geoid,neighborhood,council_district,zip_code,longitude,latitude,ESRI_OID
0,-83.026085,42.346780,523676-2900,Chene Ct & Chene St,DAMAGE TO PROPERTY,ASSAULT AND BATTERY/SIMPLE ASSAULT,2900,29000,DAMAGE TO PROPERTY,2020/04/28 19:20:00+00,...,2004280227,0710,07,2.616352e+14,Elmwood Park,5.0,48207.0,-83.026085,42.346780,1
1,-83.198644,42.399313,422988-1301,Greenfield Rd & Chalfonte St,ASSAULT,ASSAULT AND BATTERY/SIMPLE ASSAULT,1301,13001,ASSAULT AND BATTERY/SIMPLE ASSAULT,2019/08/20 04:00:00+00,...,1908200084,0814,08,2.616354e+14,Grand River-St Marys,1.0,48227.0,-83.198644,42.399313,2
2,-83.171395,42.400014,924982-2402,Chalfonte St & Steel St,STOLEN PROPERTY,MOTOR VEHICLE AS STOLEN PROPERTY (RECOVERED ONLY),2402,24002,MOTOR VEHICLE AS STOLEN PROPERTY (RECOVERED ON...,2023/02/09 21:44:00+00,...,2302090245,0203,02,2.616354e+14,Bethune Community,2.0,48227.0,-83.171395,42.400014,3
3,-83.206340,42.403139,1245613-2202,Keeler St & Saint Marys St,BURGLARY,BURGLARY - ENTRY WITHOUT FORCE (INTENT TO COMMIT),2202,22002,BURGLARY - ENTRY WITHOUT FORCE (INTENT TO COMM...,2025/02/11 22:00:00+00,...,2502190118,0812,08,2.616354e+14,Crary/St Marys,1.0,48227.0,-83.206340,42.403139,4
4,-83.278563,42.436149,1253409-2601,Telegraph Rd & Pembroke Ave,FRAUD,FRAUD - FALSE PRETENSE / SWINDLE / CONFIDENCE ...,2601,26001,FRAUD - FALSE PRETENSE / SWINDLE / CONFIDENCE ...,2025/02/21 17:30:00+00,...,2503120182,0801,08,2.616354e+14,Five Points,1.0,48219.0,-83.278563,42.436149,5

In [3]:
list(dfCrime.columns)

['X',
 'Y',
 'incident_entry_id',
 'nearest_intersection',
 'offense_category',
 'offense_description',
 'state_offense_code',
 'arrest_charge',
 'charge_description',
 'incident_occurred_at',
 'incident_time',
 'incident_day_of_week',
 'incident_hour_of_day',
 'incident_year',
 'case_id',
 'case_status',
 'case_status_updated_at',
 'updated_in_ibr_at',
 'updated_at',
 'crime_id',
 'report_number',
 'scout_car_area',
 'police_precinct',
 'census_block_2020_geoid',
 'neighborhood',
 'council_district',
 'zip_code',
 'longitude',
 'latitude',
 'ESRI_OID']

In [4]:
dfCrime = dfCrime[dfCrime['incident_year'].isin([2019, 2018, 2017])]
print(dfCrime.shape)
dfCrime.head()

(251985, 30)

,X,Y,incident_entry_id,nearest_intersection,offense_category,offense_description,state_offense_code,arrest_charge,charge_description,incident_occurred_at,...,report_number,scout_car_area,police_precinct,census_block_2020_geoid,neighborhood,council_district,zip_code,longitude,latitude,ESRI_OID
1,-83.198644,42.399313,422988-1301,Greenfield Rd & Chalfonte St,ASSAULT,ASSAULT AND BATTERY/SIMPLE ASSAULT,1301,13001,ASSAULT AND BATTERY/SIMPLE ASSAULT,2019/08/20 04:00:00+00,...,1908200084,0814,08,2.616354e+14,Grand River-St Marys,1.0,48227.0,-83.198644,42.399313,2
22,-83.175350,42.438400,75167-1302,Ward St & Pembroke Ave,AGGRAVATED ASSAULT,AGGRAVATED / FELONIOUS ASSAULT,1302,13002,AGGRAVATED / FELONIOUS ASSAULT,2017/06/14 04:30:00+00,...,1706140013,1202,12,2.616354e+14,Greenwich,2.0,48235.0,-83.175350,42.438400,23
38,-83.155044,42.420665,145600-2602,Cherrylawn St & Santa Clara St,FRAUD,FRAUD - CREDIT CARD/AUTOMATIC TELLER MACHINE,2602,26002,FRAUD - CREDIT CARD/AUTOMATIC TELLER MACHINE,2017/11/15 22:00:00+00,...,1711170268,1208,12,2.616354e+14,Bagley,2.0,48221.0,-83.155044,42.420665,39
39,-83.130331,42.331119,264806-2305,Larkins St & Michigan Ave,LARCENY,LARCENY - PERSONAL PROPERTY FROM MOTOR VEHICLE,2305,23005,LARCENY - PERSONAL PROPERTY FROM MOTOR VEHICLE,2018/09/02 02:00:00+00,...,1809020041,0405,04,2.616353e+14,Claytown,6.0,48210.0,-83.130331,42.331119,40
40,-83.180332,42.371715,75112-2900,Decatur St & Chadwick Ave,DAMAGE TO PROPERTY,DAMAGE TO PROPERTY,2900,29000,DAMAGE TO PROPERTY,2017/06/14 05:32:00+00,...,1706140009,0204,02,2.616354e+14,Paveway,7.0,48227.0,-83.180332,42.371715,41

In [6]:
list(dfCrime['offense_category'].unique())

['ASSAULT',
 'AGGRAVATED ASSAULT',
 'FRAUD',
 'LARCENY',
 'DAMAGE TO PROPERTY',
 'ARSON',
 'DANGEROUS DRUGS',
 'BURGLARY',
 'STOLEN VEHICLE',
 'ROBBERY',
 'WEAPONS OFFENSES',
 'SEXUAL ASSAULT',
 'SEX OFFENSES',
 'OBSTRUCTING JUDICIARY',
 'OTHER',
 'OUIL',
 'FAMILY OFFENSE',
 'MISCELLANEOUS',
 'OBSTRUCTING THE POLICE',
 'STOLEN PROPERTY',
 'DISORDERLY CONDUCT',
 'LIQUOR',
 'FORGERY',
 'RUNAWAY',
 'HOMICIDE',
 'KIDNAPPING',
 'EXTORTION',
 'JUSTIFIABLE HOMICIDE',
 'SOLICITATION',
 'GAMBLING']

In [7]:
violentCrimes = ['AGGRAVATED ASSAULT', 'SEXUAL ASSAULT', 'ROBBERY', 'HOMICIDE']
propertyCrimes = ['LARCENY', 'BURGLARY', 'STOLEN VEHICLE', 'STOLEN PROPERTY']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['offense_category'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(122074, 30)

,X,Y,incident_entry_id,nearest_intersection,offense_category,offense_description,state_offense_code,arrest_charge,charge_description,incident_occurred_at,...,report_number,scout_car_area,police_precinct,census_block_2020_geoid,neighborhood,council_district,zip_code,longitude,latitude,ESRI_OID
22,-83.175350,42.438400,75167-1302,Ward St & Pembroke Ave,AGGRAVATED ASSAULT,AGGRAVATED / FELONIOUS ASSAULT,1302,13002,AGGRAVATED / FELONIOUS ASSAULT,2017/06/14 04:30:00+00,...,1706140013,1202,12,2.616354e+14,Greenwich,2.0,48235.0,-83.175350,42.438400,23
39,-83.130331,42.331119,264806-2305,Larkins St & Michigan Ave,LARCENY,LARCENY - PERSONAL PROPERTY FROM MOTOR VEHICLE,2305,23005,LARCENY - PERSONAL PROPERTY FROM MOTOR VEHICLE,2018/09/02 02:00:00+00,...,1809020041,0405,04,2.616353e+14,Claytown,6.0,48210.0,-83.130331,42.331119,40
53,-82.936642,42.416444,148289-2303,Cadieux Rd & Harper Ave,LARCENY,LARCENY - THEFT FROM BUILDING,2303,23003,LARCENY - THEFT FROM BUILDING,2017/11/17 21:30:00+00,...,1711170318,0504,05,2.616350e+14,East English Village,4.0,48224.0,-82.936642,42.416444,54
59,-83.244260,42.411144,149230-2307,Grand River Ave & Patton St,LARCENY,LARCENY - OTHER,2307,23007,LARCENY - OTHER,2017/11/12 21:30:00+00,...,1711130181,0810,08,2.616354e+14,McNichols Evergreen,1.0,48219.0,-83.244260,42.411144,60
111,-82.933102,42.404882,264799-1302,Bishop St & E Warren Ave,AGGRAVATED ASSAULT,AGGRAVATED / FELONIOUS ASSAULT,1302,13002,AGGRAVATED / FELONIOUS ASSAULT,2018/09/02 03:48:00+00,...,1809020002,0504,05,2.616350e+14,East English Village,4.0,48224.0,-82.933102,42.404882,112

In [8]:
dfCrime = dfCrime[['offense_category', 'X', 'Y']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['X'], row['Y']), axis=1)
dfCrime = dfCrime[['offense_category', 'geometry']]
dfCrime.head()

       offense_category                                    geometry
22   AGGRAVATED ASSAULT  POINT (-83.1753495899552 42.4383997696895)
39              LARCENY  POINT (-83.1303310688437 42.3311189134693)
53              LARCENY  POINT (-82.9366415421032 42.4164444333366)
59              LARCENY  POINT (-83.2442600118885 42.4111443207558)
111  AGGRAVATED ASSAULT   POINT (-82.933102007526 42.4048824340372)

In [9]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_26_bg_500k/cb_2018_26_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(8164, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,26,055,551200,1,1500000US260555512001,260555512001,1,BG,825170,960628,"POLYGON ((-85.624 44.764, -85.624 44.766, -85...."
1,26,021,000800,2,1500000US260210008002,260210008002,2,BG,3119415,3214089,"POLYGON ((-86.501 42.085, -86.49 42.105, -86.4..."
2,26,055,551000,1,1500000US260555510001,260555510001,1,BG,1408711,760619,"POLYGON ((-85.595 44.766, -85.595 44.766, -85...."
3,26,057,000700,1,1500000US260570007001,260570007001,1,BG,93240804,13328,"POLYGON ((-84.488 43.328, -84.488 43.331, -84...."
4,26,125,156400,2,1500000US261251564002,261251564002,2,BG,3006649,96607,"POLYGON ((-83.362 42.573, -83.357 42.574, -83...."

In [10]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

       offense_category                geometry
22   AGGRAVATED ASSAULT  POINT (-83.175 42.438)
39              LARCENY   POINT (-83.13 42.331)
53              LARCENY  POINT (-82.937 42.416)
59              LARCENY  POINT (-83.244 42.411)
111  AGGRAVATED ASSAULT  POINT (-82.933 42.405)

In [11]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(122074, 13)

,offense_category,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
22,AGGRAVATED ASSAULT,POINT (-83.175 42.438),3058.0,26,163,539200,1,1500000US261635392001,261635392001,1,BG,199076.0,0.0
39,LARCENY,POINT (-83.13 42.331),6291.0,26,163,525700,3,1500000US261635257003,261635257003,3,BG,419124.0,0.0
53,LARCENY,POINT (-82.937 42.416),1135.0,26,163,501500,5,1500000US261635015005,261635015005,5,BG,562650.0,0.0
59,LARCENY,POINT (-83.244 42.411),1372.0,26,163,543200,1,1500000US261635432001,261635432001,1,BG,460335.0,0.0
111,AGGRAVATED ASSAULT,POINT (-82.933 42.405),5704.0,26,163,501400,3,1500000US261635014003,261635014003,3,BG,338879.0,0.0

In [12]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US261635172001    517.000000
1500000US261635189001    329.333333
1500000US261635208001    290.333333
1500000US261635214001    238.666667
1500000US261635207001    201.666667
                            ...
1500000US261635512005      0.333333
1500000US261635753003      0.333333
1500000US261251730001      0.333333
1500000US261635772001      0.333333
1500000US261635504002      0.333333
Name: count, Length: 1008, dtype: float64

In [13]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Detroit_All_Crime_BG.csv')

In [14]:
result2 = result[result['offense_category'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US261635172001    89.333333
1500000US261635189001    47.000000
1500000US261635410003    45.333333
1500000US261635007003    44.666667
1500000US261635050002    44.666667
                           ...
1500000US261635771002     0.333333
1500000US261251713001     0.333333
1500000US261635772001     0.333333
1500000US261635530002     0.333333
1500000US261251623001     0.333333
Name: count, Length: 963, dtype: float64

In [15]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Detroit_Violent_Crime_BG.csv')

In [16]:
result3 = result[result['offense_category'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US261635172001    427.666667
1500000US261635189001    282.333333
1500000US261635208001    256.000000
1500000US261635214001    227.000000
1500000US261635207001    173.666667
                            ...
1500000US261635554001      0.333333
1500000US261635748001      0.333333
1500000US261635512005      0.333333
1500000US261635753003      0.333333
1500000US261635530001      0.333333
Name: count, Length: 987, dtype: float64

In [22]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Detroit_Property_Crime_BG.csv')

In [23]:
result4 = result[result['offense_category'].isin(['STOLEN VEHICLE'])]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US261635172001    54.000000
1500000US261635208001    38.000000
1500000US261635171001    34.666667
1500000US261635165001    34.666667
1500000US261635189001    32.666667
                           ...
1500000US261635556002     0.333333
1500000US261251725001     0.333333
1500000US261635515002     0.333333
1500000US261635743001     0.333333
1500000US261251623001     0.333333
Name: count, Length: 932, dtype: float64

In [27]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/Detroit_MV_Crime_BG.csv')