In [1]:
import numpy as np
import pandas as pd
import geopandas as gpd
from shapely.geometry import Point

In [2]:
dfCrime = pd.read_csv('/Users/austincoffelt/Documents/Rent-Walk-Local/Raleigh_Police_Incidents_(NIBRS).csv')
print(dfCrime.shape)
dfCrime.head()

(564584, 23)

,X,Y,OBJECTID,GlobalID,case_number,crime_category,crime_code,crime_description,crime_type,reported_block_address,...,reported_date,reported_year,reported_month,reported_day,reported_hour,reported_dayofwk,latitude,longitude,agency,updated_date
0,NaN,NaN,12001,9cdee08d-11c8-4789-864b-6965a1b2e620,NaN,MISCELLANEOUS,81H,Miscellaneous/Missing Person (18 & over),NaN,NaN,...,2017/01/15 03:28:00+00,2017,1,14,22,Saturday,0.0,0.0,RPD,2017/01/19 20:11:28.950+00
1,NaN,NaN,12002,6f6731f4-dd64-44c7-895c-555de2703c8a,NaN,MISCELLANEOUS,81A,Miscellaneous/All Other Non-Offenses,NaN,NaN,...,2017/07/29 12:35:00+00,2017,7,29,8,Saturday,0.0,0.0,RPD,2017/08/01 14:06:50.553+00
2,NaN,NaN,12003,f0fd0e92-448e-4ca8-86c9-e6594564318b,NaN,MISCELLANEOUS,81F,Miscellaneous/Mental Commitment,NaN,NaN,...,2016/03/07 03:52:00+00,2016,3,6,22,Sunday,0.0,0.0,RPD,2016/04/14 14:43:38.923+00
3,NaN,NaN,12004,8a212e84-7b53-478a-b225-c212aa25d7fd,NaN,MISCELLANEOUS,81A,Miscellaneous/All Other Non-Offenses,NaN,NaN,...,2015/03/24 04:59:00+00,2015,3,24,0,Tuesday,0.0,0.0,RPD,2015/03/25 19:24:28.430+00
4,NaN,NaN,12005,01614b98-48f5-4374-a561-17c4b29d8857,NaN,MISCELLANEOUS,81A,Miscellaneous/All Other Non-Offenses,NaN,NaN,...,2015/12/23 00:57:00+00,2015,12,22,19,Tuesday,0.0,0.0,RPD,2016/01/13 19:29:51.767+00

In [3]:
list(dfCrime.columns)

['X',
 'Y',
 'OBJECTID',
 'GlobalID',
 'case_number',
 'crime_category',
 'crime_code',
 'crime_description',
 'crime_type',
 'reported_block_address',
 'city_of_incident',
 'city',
 'district',
 'reported_date',
 'reported_year',
 'reported_month',
 'reported_day',
 'reported_hour',
 'reported_dayofwk',
 'latitude',
 'longitude',
 'agency',
 'updated_date']

In [4]:
dfCrime = dfCrime[dfCrime['reported_year'].isin([2019, 2018, 2017])]
print(dfCrime.shape)
dfCrime.head()

(151587, 23)

,X,Y,OBJECTID,GlobalID,case_number,crime_category,crime_code,crime_description,crime_type,reported_block_address,...,reported_date,reported_year,reported_month,reported_day,reported_hour,reported_dayofwk,latitude,longitude,agency,updated_date
0,NaN,NaN,12001,9cdee08d-11c8-4789-864b-6965a1b2e620,NaN,MISCELLANEOUS,81H,Miscellaneous/Missing Person (18 & over),NaN,NaN,...,2017/01/15 03:28:00+00,2017,1,14,22,Saturday,0.0,0.0,RPD,2017/01/19 20:11:28.950+00
1,NaN,NaN,12002,6f6731f4-dd64-44c7-895c-555de2703c8a,NaN,MISCELLANEOUS,81A,Miscellaneous/All Other Non-Offenses,NaN,NaN,...,2017/07/29 12:35:00+00,2017,7,29,8,Saturday,0.0,0.0,RPD,2017/08/01 14:06:50.553+00
6,NaN,NaN,12007,2ced1b2c-90b2-47d1-b1fa-cff061abfe0a,NaN,MISCELLANEOUS,81K,Miscellaneous/Overdose Death,NaN,NaN,...,2017/04/10 22:28:00+00,2017,4,10,18,Monday,0.0,0.0,RPD,2019/12/11 08:12:00.969+00
7,NaN,NaN,12008,48a50e6e-b409-4d99-b21c-412bfe4fad78,NaN,MISCELLANEOUS,81A,Miscellaneous/All Other Non-Offenses,NaN,NaN,...,2017/11/01 18:59:00+00,2017,11,1,14,Wednesday,0.0,0.0,RPD,2018/04/13 18:22:56.433+00
14,NaN,NaN,12017,f6268ae5-5572-467c-aa5f-7070881f60b1,NaN,MISCELLANEOUS,81A,Miscellaneous/All Other Non-Offenses,NaN,NaN,...,2017/12/01 01:03:00+00,2017,11,30,20,Thursday,0.0,0.0,RPD,2018/04/13 19:01:51.523+00

In [5]:
list(dfCrime['crime_description'].unique())

['Miscellaneous/Missing Person (18 & over)',
 'Miscellaneous/All Other Non-Offenses',
 'Miscellaneous/Overdose Death',
 'Miscellaneous/Lost Property',
 'Miscellaneous/Deceased Person',
 'Family Offenses/Nonviolent (eg: neglect)',
 'Miscellaneous/Found Property',
 'Sex Offense/Forcible Rape',
 'Sex Offense/Forcible Sodomy',
 'Miscellaneous/Overdose',
 'Miscellaneous/Suicide',
 'Miscellaneous/Mental Commitment',
 'Sex Offense/Forcible Fondling',
 'Sex Offense/Peeping Tom',
 'Miscellaneous/Injured Person',
 'Traffic/Citizen Request',
 'Juvenile/Runaway',
 'Child Abuse/Simple',
 'Miscellaneous/Missing Person (17 & under)',
 'Sex Offense/Statutory Rape',
 'Sex Offense/Assault with an Object',
 'Sex Offense/Incest',
 'Assault/Simple',
 'Fraud/False Pretense or Swindle',
 'All Other/Damage to Property (minor)',
 'Juvenile/Truancy',
 'Larceny/Theft from Motor Vehicle',
 'All Other/All Other Offenses',
 'Weapons/Carry Concealed Weapon',
 'Larceny/All Other',
 'Assault/Aggravated',
 'Traffic/DWI (Driving While Impaired)',
 'Humane/Injured Person',
 'Damage to Property (Group A)',
 'Humane/Chemical Deployment',
 'Fraud/Credit Card-ATM Fraud',
 'Arson',
 'Fraud/ID Theft',
 'Humane/Animal Bite',
 'Weapons/Illegal Possession of Weapon',
 'Humane/Injured Animal',
 'Counterfeiting/Forgery',
 'Robbery/From Person',
 'Drug Violation/Misdemeanor',
 'Motor Vehicle Theft',
 'Burglary/Residential',
 'Humane/All Other Humane',
 'Weapons/Shots Fired',
 'Fraud/Welfare Fraud',
 'Stolen Property/Recover Stolen Vehicle (no arrest) (STOLEN FROM OTHER JURISDICTION)',
 'All Other/Harassing Telephone Calls',
 'Drug Violation/Felony',
 'Humane/Rabies Test',
 'Assault/Intimidation-Communicating Threats',
 'Fraud/Worthless-Bad Checks',
 'Larceny/Theft of MV Parts-Accessories',
 'Stolen Property/Possess Stolen Vehicle (w/ Arrest) (STOLEN FROM OTHER JURISDICTION)',
 'Larceny/Theft from Building',
 'All Other/Noise Ordinance Violation',
 'Drug Equipment/Paraphernalia',
 'Humane/Pick Up Animal(s)',
 'Sex Offense/Indecent Exposure',
 'Robbery/From Business',
 'Embezzlement',
 'Larceny/Shoplifting',
 'Burglary/Commercial or Non-Residential',
 'Stolen Property/Possession (w/ Arrest) (STOLEN FROM OTHER JURISDICTION)',
 'Disorderly Conduct/Resist-Delay-Obstruct Officer',
 'Humane/Vicious Animal',
 'All Other/Trespassing',
 'Disorderly Conduct/Drunk-Disorderly',
 'Disorderly Conduct/Begging',
 'Extortion/Blackmail',
 'Liquor-Alcohol Law Violations',
 'All Other/Unauthorized Use of Vehicle',
 'Fraud/Wire Fraud',
 'Humane/Animal Cruelty',
 'Larceny/Pocket-Picking',
 'Stolen Property/Recover Stolen Property (no arrest) (STOLEN FROM OTHER JURISDICTION)',
 'Larceny/Purse-Snatching',
 'Disorderly Conduct/Disturbing the Peace',
 'Kidnapping/Abduction',
 'Homicide/Murder-Nonnegligent Manslaughter',
 'Prostitution/Purchasing',
 'Larceny/Theft from Coin-Operated Machine',
 'Human Trafficking/Commercial Sex Acts',
 'Disorderly Conduct/All Other',
 'Prostitution/Engaging',
 'Weapons/All Other',
 'Fraud/Impersonation of LEO',
 'Fraud/Rental Car Conversion',
 'Prostitution/Assisting-Promoting',
 'Humane/Stray',
 'Forgery/Prescription Fraud',
 'MISC/ALL OTHER / NO OFFENSE COMMITTED',
 'Pornography/Obscene Material',
 'FRAUD/ALL OTHER',
 'FRAUD/FALSE PRETENSE',
 'Human Trafficking/Involuntary Servitude',
 'FRAUD/CREDIT CARD FRAUD',
 'LARCENY/SHOPLIFTING',
 'Humane/Noisy Animal',
 'DAMAGE TO PROPERTY/PRIVATE PROPERTY',
 'Homicide/Negligent Manslaughter',
 'Child Abuse/Aggravated',
 'Bribery',
 'FRAUD/ALL OTHER / IDENTITY THEFT',
 'ALL OTHER/ALL OTHER OFFENSES (COMM.THREATS, ETC.)',
 'Gambling/Betting-Wagering',
 'ALL OTHER/TRESPASSING',
 'Gambling/Operating-Promotion-Assisting',
 'Homicide/Justifiable Homicide']

In [7]:
violentCrimes = [
    'Homicide/Murder-Nonnegligent Manslaughter',
    'Homicide/Negligent Manslaughter',
    'Robbery/From Person',
    'Robbery/From Business',
    'Assault/Aggravated',
    'Sex Offense/Forcible Rape',
    'Sex Offense/Forcible Fondling',
    'Sex Offense/Forcible Sodomy',
    'Sex Offense/Assault with an Object',
    'Child Abuse/Aggravated',
    'Human Trafficking/Involuntary Servitude']
propertyCrimes = ['Motor Vehicle Theft', 'Burglary/Residential', 'Burglary/Commercial or Non-Residential', 'Larceny/All Other',
                  'Larceny/Theft from Motor Vehicle', 'Larceny/Theft from Building', 'Larceny/Purse-Snatching',
                  'Larceny/Theft of MV Parts-Accessories', 'Larceny/Shoplifting', 'Larceny/Pocket-Picking']
both = violentCrimes + propertyCrimes
dfCrime = dfCrime[dfCrime['crime_description'].isin(both)]
print(dfCrime.shape)
dfCrime.head()

(39417, 23)

,X,Y,OBJECTID,GlobalID,case_number,crime_category,crime_code,crime_description,crime_type,reported_block_address,...,reported_date,reported_year,reported_month,reported_day,reported_hour,reported_dayofwk,latitude,longitude,agency,updated_date
53,NaN,NaN,12063,e19ffa3d-08f0-4da8-ac1a-fabb043568db,NaN,SEX OFFENSES,17A,Sex Offense/Forcible Rape,CRIMES AGAINST PERSONS,NaN,...,2017/09/16 19:06:00+00,2017,9,16,15,Saturday,0.0,0.0,RPD,2021/01/28 11:48:11.070+00
66,NaN,NaN,12080,07e38a48-7510-44aa-aae0-6b892fdec32b,NaN,SEX OFFENSES,17B,Sex Offense/Forcible Sodomy,CRIMES AGAINST PERSONS,NaN,...,2017/11/27 22:18:00+00,2017,11,27,17,Monday,0.0,0.0,RPD,2021/01/28 11:47:58.797+00
262,NaN,NaN,12302,843a77ec-145d-4c0a-9fba-6a23b2b1dcca,NaN,SEX OFFENSES,17D,Sex Offense/Forcible Fondling,CRIMES AGAINST PERSONS,NaN,...,2017/07/25 07:05:00+00,2017,7,25,3,Tuesday,0.0,0.0,RPD,2017/07/29 13:30:38.507+00
707,NaN,NaN,12852,7ab0726c-d710-49bb-bde3-a59b7a16d41d,NaN,SEX OFFENSES,17A,Sex Offense/Forcible Rape,CRIMES AGAINST PERSONS,NaN,...,2017/06/04 11:42:00+00,2017,6,4,7,Sunday,0.0,0.0,RPD,2024/03/07 21:09:44.787+00
836,NaN,NaN,13018,e41dceea-593a-4db0-aa52-6f05eb58652a,NaN,SEX OFFENSES,17A,Sex Offense/Forcible Rape,CRIMES AGAINST PERSONS,NaN,...,2017/09/28 12:18:00+00,2017,9,28,8,Thursday,0.0,0.0,RPD,2019/06/07 17:49:58.213+00

In [8]:
dfCrime = dfCrime[['crime_description', 'latitude', 'longitude']]

# make our lon and lat into a point type for spacial join
dfCrime['geometry'] = dfCrime.apply(lambda row: Point(row['longitude'], row['latitude']), axis=1)
dfCrime = dfCrime[['crime_description', 'geometry']]
dfCrime.head()

                 crime_description     geometry
53       Sex Offense/Forcible Rape  POINT (0 0)
66     Sex Offense/Forcible Sodomy  POINT (0 0)
262  Sex Offense/Forcible Fondling  POINT (0 0)
707      Sex Offense/Forcible Rape  POINT (0 0)
836      Sex Offense/Forcible Rape  POINT (0 0)

In [9]:
# Read shapefile (automatically loads .shp, .shx, .dbf)
gdf = gpd.read_file("/Users/austincoffelt/Documents/Rent-Walk-Local/cb_2018_37_bg_500k/cb_2018_37_bg_500k.shp")

# View the first 5 rows
print(gdf.shape)
gdf.head()

(6137, 11)

,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER,geometry
0,37,019,020512,3,1500000US370190205123,370190205123,3,BG,995208,422576,"POLYGON ((-78.44 33.896, -78.439 33.896, -78.4..."
1,37,175,960300,5,1500000US371759603005,371759603005,5,BG,804486,0,"POLYGON ((-82.741 35.224, -82.738 35.227, -82...."
2,37,119,006209,1,1500000US371190062091,371190062091,1,BG,1128213,10851,"POLYGON ((-80.888 35.452, -80.889 35.46, -80.8..."
3,37,067,002903,1,1500000US370670029031,370670029031,1,BG,2146095,3772,"POLYGON ((-80.225 36.159, -80.222 36.162, -80...."
4,37,191,000401,3,1500000US371910004013,371910004013,3,BG,2531223,0,"POLYGON ((-77.918 35.347, -77.915 35.349, -77...."

In [10]:
# make sure points match the crs of gdf
gdfPoints = gpd.GeoDataFrame(
    dfCrime, 
    geometry='geometry',
    crs="EPSG:4269"  # WGS84 coordinate reference system
)
gdfPoints.head()

                 crime_description     geometry
53       Sex Offense/Forcible Rape  POINT (0 0)
66     Sex Offense/Forcible Sodomy  POINT (0 0)
262  Sex Offense/Forcible Fondling  POINT (0 0)
707      Sex Offense/Forcible Rape  POINT (0 0)
836      Sex Offense/Forcible Rape  POINT (0 0)

In [11]:
# Basic spatial join (points within polygons)
result = gpd.sjoin(
    gdfPoints, 
    gdf,
    how="left",       # 'left', 'right', or 'inner'
    predicate="within" # Spatial relationship
)
print(result.shape)
result.head()

(39417, 13)

,crime_description,geometry,index_right,STATEFP,COUNTYFP,TRACTCE,BLKGRPCE,AFFGEOID,GEOID,NAME,LSAD,ALAND,AWATER
53,Sex Offense/Forcible Rape,POINT (0 0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
66,Sex Offense/Forcible Sodomy,POINT (0 0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
262,Sex Offense/Forcible Fondling,POINT (0 0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
707,Sex Offense/Forcible Rape,POINT (0 0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
836,Sex Offense/Forcible Rape,POINT (0 0),NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
crime = result['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US371830540151    676.666667
1500000US371830501001    446.666667
1500000US371830537171    383.333333
1500000US371830540181    329.666667
1500000US371830527012    278.333333
                            ...
1500000US371830511021      0.333333
1500000US371830535122      0.333333
1500000US371830538061      0.333333
1500000US371830528021      0.333333
1500000US371830538051      0.333333
Name: count, Length: 246, dtype: float64

In [13]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/ral_All_Crime_BG.csv')

In [14]:
result2 = result[result['crime_description'].isin(violentCrimes)]
crime = result2['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US371830501001    61.333333
1500000US371830527051    37.000000
1500000US371830527073    35.666667
1500000US371830545002    34.000000
1500000US371830540181    29.000000
                           ...
1500000US371830540161     0.333333
1500000US371830541103     0.333333
1500000US371830537071     0.333333
1500000US371830515022     0.333333
1500000US371830528021     0.333333
Name: count, Length: 216, dtype: float64

In [20]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/ral_Violent_Crime_BG.csv')

In [21]:
result3 = result[result['crime_description'].isin(propertyCrimes)]
crime = result3['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US371830540151    660.000000
1500000US371830501001    385.333333
1500000US371830537171    375.000000
1500000US371830540181    300.666667
1500000US371830527012    259.000000
                            ...
1500000US371830535171      0.333333
1500000US371830530053      0.333333
1500000US371830537203      0.333333
1500000US371830530031      0.333333
1500000US371830538051      0.333333
Name: count, Length: 244, dtype: float64

In [23]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/ral_Property_Crime_BG.csv')

In [33]:
result4 = result[result['crime_description'].isin(['Motor Vehicle Theft'])]
crime = result4['AFFGEOID'].value_counts() / 3
crime

AFFGEOID
1500000US371830501001    34.666667
1500000US371830540141    20.666667
1500000US371830540181    18.333333
1500000US371830540151    17.000000
1500000US371830527051    16.333333
                           ...
1500000US371830517002     0.333333
1500000US371830537122     0.333333
1500000US371830518002     0.333333
1500000US371830515022     0.333333
1500000US371830537112     0.333333
Name: count, Length: 221, dtype: float64

In [35]:
# export as a csv
crime.to_csv('/Users/austincoffelt/Documents/RW Data/ral_MV_Crime_BG.csv')